### ISSUE TITLE
ERROR IN register

### ISSUE THREAD

**Issue by niexiaoqing** [STOmics/SAW#100]
run test data and get a error info:
![image](https://github.com/STOmics/SAW/assets/23168361/83002ff9-8c5a-4b7b-bf9b-d0828223965d)
need help.

**Comment by Jinghao-Chen** [comment]
The versions of this demo data and SAW do not correspond. Please read the https://github.com/STOmics/SAW/blob/main/Test_Data/README.md to select the corresponding demo data and SAW.

**Comment by niexiaoqing** [comment]
> The versions of this demo data and SAW do not correspond. Please read the https://github.com/STOmics/SAW/blob/main/Test_Data/README.md to select the corresponding demo data and SAW.
thanks
