### ISSUE TITLE
no <stainType>_SN_mask.tif file in 04.register directory

### ISSUE THREAD

**Issue by niexiaoqing** [STOmics/SAW#102]
run imageTools ipr2img and get no <stainType>_SN_mask.tif file in 04.register. after run  imageTools ipr2img  got fiiles below
![image](https://github.com/STOmics/SAW/assets/23168361/65a98629-dad2-4ea0-9e05-3d97ee525ef3)

**Comment by Jinghao-Chen** [comment]
Did you set the parameter '-doCellBin' as 'Y' when you ran the pipeline script?

**Comment by niexiaoqing** [comment]
> Did you set the parameter '-doCellBin' as 'Y' when you ran the pipeline script?

which script?    i run the shell as below 
![image](https://github.com/STOmics/SAW/assets/23168361/57d646bb-2a6d-4478-b3cb-d85faa248cb5)
and before that i run register as follow
![image](https://github.com/STOmics/SAW/assets/23168361/eb5b6b2f-7d32-48be-9d68-2a9d04ee070a)

**Comment by Jinghao-Chen** [comment]
@niexiaoqing Did you set the parameter '-w' as 'True' in register and '-d' as 'tissue cell' in ipr2img? If so, could you provide the 20240422-09-30-16.log, 20240423-00-47-05.log and the *.ipr in 04.register?

**Comment by niexiaoqing** [comment]
> @niexiaoqing Did you set the parameter '-w' as 'True' in register and '-d' as 'tissue cell' in ipr2img? If so, could you provide the 20240422-09-30-16.log, 20240423-00-47-05.log and the *.ipr in 04.register?
[3files.tar.gz](https://github.com/STOmics/SAW/files/15070790/3files.tar.gz)
![image](https://github.com/STOmics/SAW/assets/23168361/55df4eb0-7da6-4007-bdbe-83e27992a08b)

![image](https://github.com/STOmics/SAW/assets/23168361/84736aa3-a9f2-42dd-a3ef-845a2370c541)

**Comment by niexiaoqing** [comment]
> @niexiaoqing Did you set the parameter '-w' as 'True' in register and '-d' as 'tissue cell' in ipr2img? If so, could you provide the 20240422-09-30-16.log, 20240423-00-47-05.log and the *.ipr in 04.register?

I know way ,  lack a "  " between word "cell" and "\\"

**Comment by Jinghao-Chen** [comment]
> > @niexiaoqing Did you set the parameter '-w' as 'True' in register and '-d' as 'tissue cell' in ipr2img? If so, could you provide the 20240422-09-30-16.log, 20240423-00-47-05.log and the *.ipr in 04.register?
> 
> I know way , lack a " " between word "cell" and "\"

Okay, glad that your problem is solved.

**Comment by niexiaoqing** [comment]
> > > @niexiaoqing Did you set the parameter '-w' as 'True' in register and '-d' as 'tissue cell' in ipr2img? If so, could you provide the 20240422-09-30-16.log, 20240423-00-47-05.log and the *.ipr in 04.register?
> > 
> > 
> > I know way , lack a " " between word "cell" and ""
> 
> Okay, glad that your problem is solved.

thank you but I get another trouble.  run repoter command and got follow message:
![image](https://github.com/STOmics/SAW/assets/23168361/5854463f-dc3b-4b83-ac4f-e62af7b306a0)

**Comment by niexiaoqing** [comment]
in addition ,in 061.cellcluster step i got result 
![image](https://github.com/STOmics/SAW/assets/23168361/0465572e-584a-4adb-9231-4aced73bff79)
not as manual descripted as follow
![image](https://github.com/STOmics/SAW/assets/23168361/3cba62e8-4463-4233-8072-b99395da90f7)

**Comment by Jinghao-Chen** [comment]
Could you provide the script of these steps, tissueCut, cellCluster and report?

**Comment by niexiaoqing** [comment]
> Could you provide the script of these steps, tissueCut, cellCluster and report?

![image](https://github.com/STOmics/SAW/assets/23168361/698516db-4ffc-4ada-8001-971ca11f736d)
![image](https://github.com/STOmics/SAW/assets/23168361/385a7b55-0583-4501-8937-3624ec04a0bf)
![image](https://github.com/STOmics/SAW/assets/23168361/6bed912b-9157-48b9-a543-3cc54c21d782)

**Comment by Jinghao-Chen** [comment]
In the _cellCluster_ step, the parameter '-o' should be set as '${SN}.adjusted.cell.cluster.h5ad'.
In the _report_ step, the parameter '-n' should be set as '${SN}.gef', which was generated from 02.count/${SN}.raw.gef by _cellCut bgef_

**Comment by niexiaoqing** [comment]
> bgef

thanks, i get another err:
![image](https://github.com/STOmics/SAW/assets/23168361/8bbbd988-6106-4f13-97ed-7fd56fc85dec)
in report step

**Comment by Jinghao-Chen** [comment]
Which parameter did you set as 'A02677B5.cellbin.gef'?

**Comment by niexiaoqing** [comment]
> Which parameter did you set as 'A02677B5.cellbin.gef'?

![image](https://github.com/STOmics/SAW/assets/23168361/c672177d-87bc-4c6e-a70a-b9e12f5dd168)

**Comment by Jinghao-Chen** [comment]
In the report step, which parameter did you set as 'A02677B5.cellbin.gef'? '-n' or '--cellBinGef'?

**Comment by niexiaoqing** [comment]
> In the report step, which parameter did you set as 'A02677B5.cellbin.gef'? '-n' or '--cellBinGef'?

-n

**Comment by Jinghao-Chen** [comment]
It is suggested that you set '-n' as '${SN}.gef', not '${SN}.cellbin.gef'. For generating ${SN}.gef, reference is as follow:
![image](https://github.com/STOmics/SAW/assets/58293762/823fa0d4-38f6-46b7-a602-e5bd623b10f2)

**Comment by niexiaoqing** [comment]
> It is suggested that you set '-n' as '${SN}.gef', not '${SN}.cellbin.gef'. For generating ${SN}.gef, reference is as follow: ![image](https://private-user-images.githubusercontent.com/58293762/324768249-823fa0d4-38f6-46b7-a602-e5bd623b10f2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM4NjQ0NjUsIm5iZiI6MTcxMzg2NDE2NSwicGF0aCI6Ii81ODI5Mzc2Mi8zMjQ3NjgyNDktODIzZmEwZDQtMzhmNi00NmI3LWE2MDItZTViZDYyM2IxMGYyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIzVDA5MjI0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ3NzNhYTZmOTAxYmNhNjc5MWJlOWFkYzRmZTk1MDU4NjFmNDE1YTg1MTNlYzlhY2Y1ZWQxOWUxYjIxYWY2ZjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3qERy-yl0DrpfyHaQpYzk1onh45vOAut9DUT3Ple2NU)

thanks, i run report  again ,and got fellow error message
![image](https://github.com/STOmics/SAW/assets/23168361/c6077429-d178-49ae-8a47-1cd4dc7fbe7f)
and delete -i param,  no error message find  and got the html format report

**Comment by Jinghao-Chen** [comment]
> > It is suggested that you set '-n' as '${SN}.gef', not '${SN}.cellbin.gef'. For generating ${SN}.gef, reference is as follow: ![image](https://private-user-images.githubusercontent.com/58293762/324768249-823fa0d4-38f6-46b7-a602-e5bd623b10f2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM4NjQ0NjUsIm5iZiI6MTcxMzg2NDE2NSwicGF0aCI6Ii81ODI5Mzc2Mi8zMjQ3NjgyNDktODIzZmEwZDQtMzhmNi00NmI3LWE2MDItZTViZDYyM2IxMGYyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIzVDA5MjI0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ3NzNhYTZmOTAxYmNhNjc5MWJlOWFkYzRmZTk1MDU4NjFmNDE1YTg1MTNlYzlhY2Y1ZWQxOWUxYjIxYWY2ZjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3qERy-yl0DrpfyHaQpYzk1onh45vOAut9DUT3Ple2NU)
> 
> thanks, i run report again ,and got fellow error message ![image](https://private-user-images.githubusercontent.com/23168361/324775605-c6077429-d178-49ae-8a47-1cd4dc7fbe7f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM4NjU3ODEsIm5iZiI6MTcxMzg2NTQ4MSwicGF0aCI6Ii8yMzE2ODM2MS8zMjQ3NzU2MDUtYzYwNzc0MjktZDE3OC00OWFlLThhNDctMWNkNGRjN2ZiZTdmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIzVDA5NDQ0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgyMTNjYTIxMGYzYjNmNGZlOGJjNjViNWFmNzQxNDgzM2JlNmFiNTYyNGE5OWM1NWJiMjkyNWQ2YzY0NjYxYTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Q8k-TXSR9_P1scAVy9NluCPd4yLgM6eyEq0Hkq8Fm1E) and delete -i param, no error message find and got the html format report

It's okay, it was just warning. But the image may not be visible in html format report if you delete -i.
