### ISSUE TITLE
Input for stereopy 

### ISSUE THREAD

**Issue by maximelepetit** [STOmics/SAW#103]
Hello,

I have a question about input of stereopy.
I ran successfully the stereoPipeline_v7.1 pipeline with cellbin.

Now, I want run the Quick Start (cellbin) tutorial.

Which input should I use between adjusted.cellbin.gef and cellbin.gef ?

Thanks for help!

**Comment by Jinghao-Chen** [comment]
Hi, both files can be analyzed in Stereopy, depending on your analysis needs. Cellbin.gef contains the expression matrix extracted based on the cell nuclear area based on the ssDNA image, while adjusted.cellbin.gef is based on the cell nuclear area and expanded outward to include more cell expression information.

**Comment by maximelepetit** [comment]
Thanks a lot for the quick reply !

**Comment by maximelepetit** [comment]
Hi i reopen the issue because my question is related to my first question : 

What the difference between each .gef outputs ? : 

- 02.count/A02994G3.raw.gef  -> ?
- 02.count/A02994G3.gef -> ? 
- 04.tissuecut/A02994G3.DAPI.gef -> ?
- 04.tissuecut/A02994G3.tissue.gef -> ?
- 041.cellcut/A02994G3.cellbin.gef -> contains the expression matrix extracted based on the cell nuclear area based on the ssDNA image
- 041.cellcut/A02994G3.adjusted.cellbin.gef -> contains the expression matrix extracted based on the cell nuclear area and expanded outward to include more cell expression information


Thanks !

**Comment by Jinghao-Chen** [comment]
Hi,
- A02994G3.raw.gef contains the expression matrix extracted based on **the whole Stereo-seq chip** and its binsize is **bin1**.

- A02994G3.gef also contains the expression matrix extracted based on **the whole Stereo-seq chip**, with **more binsize, e.g. bin1 bin5 bin20 bin50 bin100 bin150 bin200.**

- A02994G3.tissue.gef contains the expression matrix extracted based on **the tissue area**, and its binsize is **bin1**

- A02994G3.DAPI.gef contains the expression matrix extracted based on **the tissue area** based on the DAPI image, with **more binsize** like A02994G3.gef

**Comment by maximelepetit** [comment]
Thanks a lot for the quick reply ;) 

Thats very clear for me.

Bests

Maxime
