### ISSUE TITLE
04.register's errors ？？

### ISSUE THREAD

**Issue by Boundless1** [STOmics/SAW#104]
<img width="1091" alt="image" src="https://github.com/STOmics/SAW/assets/75532200/33fcd5e9-933f-4903-96dd-e578e78a1097">
I need some help，Thank you！！

**Comment by TheSallyGardens** [comment]
@Boundless1  Hi,"OSError: [Errno 26] Text file busy error "that does not belong to SAW.
OSError with Errno 26, specifically "Text file busy," typically occurs when you try to perform an operation on a file that is currently being used by another process. The error suggests that the file "04.register/ssDNA" is in use by another program or process.
﻿
There are a few possible reasons for this error:
﻿
Another program or script has opened the file and is actively using it. It could be a text editor, database, or any other application that has locked the file for exclusive use.
﻿
The file is being accessed by a different part of your own program or script, and you haven't closed or released the file object or resource properly.
﻿
The file is located on a network or shared drive, and another user or process is currently accessing the file.
﻿
To resolve this issue, you can try the following steps:
﻿
Make sure to close the file in any other programs or processes that might be using it. Check if you have any open text editors or applications that may have the file open, and close them.
﻿
In your own code, ensure that you properly close or release the file object or resource after you have finished using it. You can use the close() method on the file object or use the with statement to automatically close the file when you're done with it.
﻿
If the file is on a network or shared drive, coordinate with other users or processes to ensure that the file is not being accessed simultaneously.
﻿
If these steps don't resolve the issue, there may be other factors at play, such as file permissions, file system limitations, or specific operating system behaviors.

**Comment by Boundless1** [comment]
> @Boundless1 Hi,"OSError: [Errno 26] Text file busy error "that does not belong to SAW. OSError with Errno 26, specifically "Text file busy," typically occurs when you try to perform an operation on a file that is currently being used by another process. The error suggests that the file "04.register/ssDNA" is in use by another program or process. ﻿ There are a few possible reasons for this error: ﻿ Another program or script has opened the file and is actively using it. It could be a text editor, database, or any other application that has locked the file for exclusive use. ﻿ The file is being accessed by a different part of your own program or script, and you haven't closed or released the file object or resource properly. ﻿ The file is located on a network or shared drive, and another user or process is currently accessing the file. ﻿ To resolve this issue, you can try the following steps: ﻿ Make sure to close the file in any other programs or processes that might be using it. Check if you have any open text editors or applications that may have the file open, and close them. ﻿ In your own code, ensure that you properly close or release the file object or resource after you have finished using it. You can use the close() method on the file object or use the with statement to automatically close the file when you're done with it. ﻿ If the file is on a network or shared drive, coordinate with other users or processes to ensure that the file is not being accessed simultaneously. ﻿ If these steps don't resolve the issue, there may be other factors at play, such as file permissions, file system limitations, or specific operating system behaviors.

Thanks, as I was operating from the shared folder, and I moved the data to a local folder can run successfully！
