### ISSUE TITLE
Test data "SS200000135TL_D1_v4_brain" does not have .ipr file ? 

### ISSUE THREAD

**Issue by Zhouchlei** [STOmics/SAW#114]
Hi, 
I noticed that the test_data 'SS200000135TL_D1_v4_brain' does not have a .ipr file, but 'SS200000135TL_D1_v5_brain' does. Since I have already downloaded the v4 data, can I use the v5 .ipr file for analyzing the v4 data?
![910c0ba60ad1d8e9b6543bc16f9b310](https://github.com/STOmics/SAW/assets/170914860/99c4bdfb-2c0b-40da-8e0e-80600171d33a)

**Comment by Jinghao-Chen** [comment]
Hi, v5 .ipr file could not be used for v4 data analysis. But if you have downloaded the fastq and mask of v4 data, you could use the .tar.gz and .ipr file of v5 data to run SAW. Please note that only SAW v5 version could be used for v5 image data.

**Comment by Zhouchlei** [comment]
> Hi, v5 .ipr file could not be used for v4 data analysis. But if you have downloaded the fastq and mask of v4 data, you could use the .tar.gz and .ipr file of v5 data to run SAW. Please note that only SAW v5 version could be used for v5 image data.

Thank you for your reply.
Additionally, I have some questions. What are the differences between the v5 and v4 data? When run SAW with fastq and mask of v4 data, and .tar.gz and .ipr file of v5 data, are there any considerations besides the SAW version?

**Comment by Jinghao-Chen** [comment]
> Thank you for your reply. Additionally, I have some questions. What are the differences between the v5 and v4 data? When run SAW with fastq and mask of v4 data, and .tar.gz and .ipr file of v5 data, are there any considerations besides the SAW version?

Hi, as you can see, for v5, we change the format of image record file from .json to .ipr for adapting software updates. The fastq and the mask in v4 & v5 data are the same.
Apart from the adaptation of pipeline script and software versions, there is no other important aspects to consider. Of course, if you encounter any problems, please feel free to contact us at any time

**Comment by Zhouchlei** [comment]
> > Thank you for your reply. Additionally, I have some questions. What are the differences between the v5 and v4 data? When run SAW with fastq and mask of v4 data, and .tar.gz and .ipr file of v5 data, are there any considerations besides the SAW version?
> 
> Hi, as you can see, for v5, we change the format of image record file from .json to .ipr for adapting software updates. The fastq and the mask in v4 & v5 data are the same. Apart from the adaptation of pipeline script and software versions, there is no other important aspects to consider. Of course, if you encounter any problems, please feel free to contact us at any time

Thanks for your patient reply! Your reply has been very helpful to me.
