### ISSUE TITLE
Fata error, sequence contains control characters

### ISSUE THREAD

**Issue by iichelhadi** [STOmics/SAW#116]
Hello,

I am trying to run SAWv7.1 using the CITE-seq data and I encounter the error below during the mapping step when running onl lane3 and lane4 samples. Lane1 and Lane2 ran fine. Are the files potentially corrupted? I downloaded them using raysync client then transfered to HPC using `rsync`.
 
Regards

![Screenshot from 2024-05-29 12-51-22](https://github.com/STOmics/SAW/assets/59079565/de1f1754-1132-40f2-9871-79e8dbddf41c)

**Comment by TheSallyGardens** [comment]
@iichelhadi  Hi!
You can obtain the MD5 file in the link, which records the MD5 value of fq file.

**Comment by iichelhadi** [comment]
thanks I am currently checking. L03_read2 and L04_read2 md5 didn't match.
