### ISSUE TITLE
 fastq-SE segmentation error

### ISSUE THREAD

**Issue by YiqianGu** [STOmics/SAW#121]
Hi team,

Thanks for you great tools.
I was running SAW_7.1 then encountered fastq-SE segmentation error. I have attached the scripts I ran and the errors.
Please kindly let me know if you need anything else to troubleshoot.

Best,
Yiqian

Scripts I ran:

#/bin/bash
ulimit -n 10240
ulimit -v 33170449147
NUMBA_CACHE_DIR=./

dataDir=/dir/to/fq
outDir=/dir/to/outdir
files=$(ls $dataDir/*.fq.gz | paste -sd ',' -)
export SINGULARITY_BIND=$dataDir,$outDir

bash stereoPipeline_v7.1.sh \
    -sif /u/home/g/guyiqian/SAW_7.1.sif \
    -splitCount 16 \
    -maskFile /dir/XXX.barcodeToPos.h5 \
    -fq1 $files  \
    -speciesName xxx \
    -tissueType skin \
    -refIndex /ref/hg38_ensembl_stereoseq \
    -annotationFile /ref/Homo_sapiens.GRCh38.111.gtf \
    -rRNAremove N \
    -threads 8 \
    -outDir $outDir \
    -doCellBin Y

Error:
--- Error: [2024-6-14 13:47:40] SAW-A10102: There is a bug in fastq-SE segmentation.
bcSTAR: ReadsParse.cpp:383: ThreadProcess(IOparam*, IOThread*)::<lambda(ThreadProcess(IOparam*, IOThread*)::FQbuf*, char*)>: Assertion `false' failed.
/usr/local/bin/mapping: line 1:  7845 Aborted                 /opt/saw_st_software/pipeline/mapping/bcSTAR $*
INFO:    Cleaning up image...
Command exited with non-zero status 134
        Command being timed: "singularity exec /u/home/g/guyiqian/SAW_7.1.sif mapping --outSAMattributes spatial --outSAMtype BAM SortedByCoordinate --genomeDir /u/scratch/g/guyiqian/ref/hg38_ensembl_stereoseq --runThreadN 8 --outFileNamePrefix /u/scratch/g/guyiqian/analysis/V24010079-B03209F113/00.mapping/03.B03209F113.Q4. --sysShell /bin/bash --stParaFile /u/scratch/g/guyiqian/analysis/V24010079-B03209F113/00.mapping/03.B03209F113.Q4.bcPara --readNameSeparator " " --limitBAMsortRAM 63168332971 --limitOutSJcollapsed 10000000 --limitIObufferSize=280000000 --outBAMsortingBinsN 50 --outSAMmultNmax 1"
        User time (seconds): 2513.00
        System time (seconds): 164.30
        Percent of CPU this job got: 686%
        Elapsed (wall clock) time (h:mm:ss or m:ss): 6:29.90
        Average shared text size (kbytes): 0
        Average unshared data size (kbytes): 0
        Average stack size (kbytes): 0
        Average total size (kbytes): 0
        Maximum resident set size (kbytes): 51315776
        Average resident set size (kbytes): 0
        Major (requiring I/O) page faults: 0
        Minor (reclaiming a frame) page faults: 69168789
        Voluntary context switches: 530030
        Involuntary context switches: 76640
        Swaps: 0
        File system inputs: 7248680
        File system outputs: 73693912
        Socket messages sent: 0
        Socket messages received: 0
        Signals delivered: 0
        Page size (bytes): 4096
        Exit status: 134

**Comment by Jinghao-Chen** [comment]
Hi, this is generally because the fq file was not read correctly. It seems that the error occurred when mapping *_3.fq.gz. You could check whether the path of *_3.fq.gz was correctly recorded in 00.mapping/03.fastq.list, check the completeness of the fq file, and confirm that it did not use a soft link.

**Comment by YiqianGu** [comment]
Thanks! That helps!
