### ISSUE TITLE
Can't pull the image because dockerhub has been close

### ISSUE THREAD

**Issue by feeisnotfree** [STOmics/SAW#124]
Can't pull the image because dockerhub has been close.
#This is my code
docker pull dockerproxy.com/stomics/saw:07.1.1
Error response from daemon: Get "https://dockerproxy.com/v2/": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)

#This is my docker daemon.json:
daemon.json{
    "registry-mirrors": [
        "https://dockerproxy.com",
        "https://docker.mirrors.ustc.edu.cn",
        "https://docker.nju.edu.cn",
        "https://docker.m.daocloud.io"
    ]
}
# The same question has happened in use singularity because it also use docker to pull the resource

**Comment by Jinghao-Chen** [comment]
This error message usually occurs when there is a problem connecting to the Docker registry or when there is a network issue, it might be helpful to check the network, proxy settings or firewall settings, and you could try to run
`docker pull stomics/saw:07.1.1`

**Comment by feeisnotfree** [comment]
> This error message usually occurs when there is a problem connecting to the Docker registry or when there is a network issue, it might be helpful to check the network, proxy settings or firewall settings, and you could try to run `docker pull stomics/saw:07.1.1`

Thanks a lot for your reply Clouate,
Yes, I know. And this is because some can speak reason and in my country all the dockerhub has been closed, and the IP of the docker has been banned. So can the software developer directly shares the download link of SAW7? For Chinese user?

**Comment by feeisnotfree** [comment]
我的英文不太好，重新表达一下，就是国内因为某些原因在6月初将dokerhub国内开放的镜像全部下架，并且中国的ip无法直接访问dockerhub。在服务器不太可能安装科学上网工具，风险太大。请开发者尽快提供替代下载方案，如提供docker封装后包的下载链接。

**Comment by Clouate** [comment]
@feeisnotfree Hi, we have received this issue and are discussing solutions. If you urgently need to use SAW v7.1.1, you could use the following link (valid for 7 days) that we temporarily provide. In addition, we plan to update SAW v7.1.2 next week.
链接： http://116.6.21.110:8090/share/30cb237f-c518-4546-9e13-e872ba352899
密码： STEREO

**Comment by Jinghao-Chen** [comment]
Hi, a few minutes ago, an email with relevant information should have been sent to you via Github email

**Comment by prayer-wu** [comment]
> Hi, a few minutes ago, an email with relevant information should have been sent to you via Github email

hi, i have the same question, when singularity build SAW_7.1.sif docker://stomics/saw:07.1.1

FATAL:   While performing build: conveyor failed to get: Get "https://production.cloudflare.docker.com/registry-v2/docker/registry/v2/blobs/sha256/26/265324fefe2ee20f2cbdc854b3533ae286ffe796b41647811452e0199ad814a4/data?verify=1720491179-UgSrQr6kae9KshSRVuvEBC4fRog%3D": dial tcp 168.143.162.58:443: i/o timeout

Can you help me with that

**Comment by Clouate** [comment]
@prayer-wu Hi, this is a temporary download link. (Valid for 6 days):
Link: http://116.6.21.110:8090/share/30cb237f-c518-4546-9e13-e872ba352899
Password: STEREO

**Comment by prayer-wu** [comment]
I got it. Thank you very much
