### ISSUE TITLE
metaclass conflict when running SAW_7.1.sif

### ISSUE THREAD

**Issue by YiqianGu** [STOmics/SAW#126]
Hi team,

My singularity version is 3.8.5, and I used SAW_7.1.sif. 
Now I am at step 041.cellCut, which is the farthest I ever got. However, I am stuck again.
The error is : TypeError: metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of all its bases.
And I also attached the log file.
Appreciate any advice.

Thanks,
Yiqian

[script.log](https://github.com/user-attachments/files/16038751/script.log)

**Comment by Jinghao-Chen** [comment]
Hi, it seems that the python environment in SAW .sif has some conflicts with your environment, you could try pip install matplotlib<3.7. By the way, if you do not need to analyze proteomic data, we recommend that you could try the reconstructed SAW v8, which will be released in a few days. SAW v8 could solve most environmental conflict problems.

**Comment by YiqianGu** [comment]
Thanks! Solved by  "singularity exec SAW_7.1.sif pip3 install matplotlib==3.6". Looking forward to using SAW v8.
