### ISSUE TITLE
Error detected in HDF5 (1.12.3) thread 0

### ISSUE THREAD

**Issue by joweihsieh** [STOmics/SAW#127]
Hi, 

Thank you for developing this tool. As I prepare to analyze our own stereo-seq data soon, I'm currently familiarizing myself with SAW by testing it with mouse embryo data (D02070C3D3). My singularity version is 3.11.0, and I used SAW_7.1.sif. However, I've encountered errors during the cellCut step. Could you please assist me in resolving this issue?

Thanks, 
Jo-Wei
===== Here are the errors =====
公曆 20廿四年 七月 三日 週三 六時二分十六秒 => cellCut start.......
create h5 file: 
HDF5-DIAG: Error detected in HDF5 (1.12.3) thread 0:
  #000: /data/users/guanyang/dev_srcs/hdf5-1.12.3/src/H5F.c line 486 in H5Fcreate(): invalid file name
    major: Invalid arguments to routine
    minor: Bad value
HDF5-DIAG: Error detected in HDF5 (1.12.3) thread 0:
  #000: /data/users/guanyang/dev_srcs/hdf5-1.12.3/src/H5G.c line 361 in H5Gcreate2(): invalid location identifier
    major: Invalid arguments to routine
    minor: Inappropriate type
TIFFOpen: -o: No such file or directory.
minx:0 miny:0 maxx:26459 maxy:44099
genecnt:26324 geneExpcnt:91970933 hashcnt:77610116
readBgef_new - elapsed time: 60223.77326 ms
read mask file error 
Command exited with non-zero status 255
        Command being timed: "singularity exec /home/woodydrylab/DiskArray/guest001/JW/bin/SAW_7.1.sif cellCut cgef -i /home/woodydrylab/DiskArray/guest001/JW/StereoSeq/mouse_embryo_out/02.count/D02070C3D3.raw.gef -m -o /home/woodydrylab/DiskArray/guest001/JW/StereoSeq/mouse_embryo_out/041.cellcut/D02070C3D3.cellbin.gef"
        User time (seconds): 54.03
        System time (seconds): 6.74
        Percent of CPU this job got: 99%
        Elapsed (wall clock) time (h:mm:ss or m:ss): 1:00.82
        Average shared text size (kbytes): 0
        Average unshared data size (kbytes): 0
        Average stack size (kbytes): 0
        Average total size (kbytes): 0
        Maximum resident set size (kbytes): 9018964
        Average resident set size (kbytes): 0
        Major (requiring I/O) page faults: 103
        Minor (reclaiming a frame) page faults: 6524141
        Voluntary context switches: 1919
        Involuntary context switches: 140
        Swaps: 0
        File system inputs: 13612
        File system outputs: 8
        Socket messages sent: 0
        Socket messages received: 0
        Signals delivered: 0
        Page size (bytes): 4096
        Exit status: 255

**Comment by Jinghao-Chen** [comment]
Hi, this error is due to the cell segmentation result file (*mask.tif) not being input correctly(-m parameter missing). You could check the 03.register directory to see if there is such a file(*mask.tif). I think there may not be, because the image result files (.ipr & .tar.gz) of this demo data we provided are not suitable for SAW v7. If you want to continue analyzing it, please go to https://www.stomics.tech/products/BioinfoTools/OfflineSoftware Download the latest ImageStudio software and use it to process .tar.gz file (Image QC), obtain new .ipr & tar.gz, and then run SAW v7

**Comment by joweihsieh** [comment]
Hi, 

As you said, there is indeed no *mask.tif in the folder of 03.register. 

Before this error, I encountered the issue "SAW-A40001: The version of 0.1.0 is too low" and already re-generated the .ipr & tar.gz by the newest version of ImageStudio 3.0.4. 

I re-ran SAW v7.1 with the new .ipr & tar.gz and the issue "SAW-A40001" did not happen but encountered another error: "Error detected in HDF5 (1.12.3) thread 0," which I posted here.

**Comment by Jinghao-Chen** [comment]
Could you show or provide us the .log file in 03.register and the log files you ran the script?

**Comment by joweihsieh** [comment]
Hi, 
I did not see log file in 03.register, so I re-ran again, but still, no log file appears in 03.register.

Here is the log file that I ran the script:
https://www.dropbox.com/scl/fi/krm8j7s490bmsoyuvtpa6/nohup.out?rlkey=e2w3ojwy5964iu7han9wc5xuw&dl=0

**Comment by Jinghao-Chen** [comment]
@joweihsieh Hi, there was no record of running the register command in your log file. Could you provide your running command or confirm whether the paths to input files such as .tar.gz and .ipr are correct and exist?

**Comment by joweihsieh** [comment]
Hi, 

I found that the error was caused by my file name, so I re-ran it yesterday, and the job is now completed.

Thanks for your help!
