### ISSUE TITLE
Problems with  data format conversion

### ISSUE THREAD

**Issue by ultraypy** [STOmics/SAW#129]
I'm sorry, there is no complete pipeline available that explains how to convert objects from Stereopy to Scanpy, especially with specific versions of Scanpy and Stereopy. The official documentation on data format conversion is not very detailed and lacks sufficient content. 
could you please help me with a more detailed pipeline

谢谢！

**Comment by ultraypy** [comment]
As well as seurat

**Comment by Jinghao-Chen** [comment]
Hi, regarding issues for Stereopy, we may have limited help. You could refer to this document, https://stereopy.readthedocs.io/en/latest/Tutorials/Format_Conversion.html
or visit Stereopy github issue page for consultation, https://github.com/STOmics/Stereopy/issues
