### ISSUE TITLE
EXITING because of FATAL PARAMETER ERROR:

### ISSUE THREAD

**Issue by GLking123** [STOmics/SAW#130]
Hello, Here's my running code.
`/public/home/software/saw-8.0.1/bin/saw makeRef \
    --mode=STAR \
    --fasta=***.genome.chr.fa \
    --gtf=***.gff3 \
    --genome=STAR_test4_ds \
`

I'm running out of memory, but my machine still has a lot of memory.The error message is as follows:

`EXITING because of FATAL PARAMETER ERROR: limitGenomeGenerateRAM=31000000000is too small for your genome
SOLUTION: please specify --limitGenomeGenerateRAM not less than 48396003370 and make that much RAM available 

Jul 11 16:20:44 ...... FATAL ERROR, exiting`

I tried to add --limitGenomeGenerateRAM 50000000000 ，The error message is as follows:
`usage: SAW [-h] [--version]
           {count,checkGTF,makeRef,reanalyze,convert,realign} ...
SAW: error: unrecognized arguments: --limitGenomeGenerateRAM 50000000000
`

For the above question, could you provide some debugging suggestions? Thank you for your valuable time and assistance. I sincerely look forward to your response！

**Comment by Jinghao-Chen** [comment]
Hi, we are sorry that the makeRef program of SAW v8.0.1 does not currently support custom STAR parameters. You could use SAW v7 mapping, which can customize the parameters of STAR, or use STAR 2.7.1a itself to build a reference genome.

**Comment by GLking123** [comment]
Thank you for your answer.
