### ISSUE TITLE
cannot build SAW via singularity

### ISSUE THREAD

**Issue by sarahshuang** [STOmics/SAW#134]
Hi,

I am encounted with the following connection error. Do you have some suggestions?

```
(base) wus@dell-PowerEdge-R750xs:~/tools/singularity-3.8.7/builddir$ ./singularity build SAW_v7.1.sif docker://stomics/saw:07.1.0 
INFO:    Starting build...
Getting image source signatures
FATAL:   While performing build: conveyor failed to get: initializing source oci:/home/wus/.singularity/cache/blob:79f0b276e249ba123d6c8016fe406185fd01c130e359e3c3a4a76711e26d0af6: reading blob sha256:265324fefe2ee20f2cbdc854b3533ae286ffe796b41647811452e0199ad814a4: Get "https://production.cloudflare.docker.com/registry-v2/docker/registry/v2/blobs/sha256/26/265324fefe2ee20f2cbdc854b3533ae286ffe796b41647811452e0199ad814a4/data?verify=1722413182-Wa1%2FI%2Fvoi9FbSMEWHYB%2F5rWzZO0%3D": dial tcp 199.16.158.8:443: i/o timeout
```

**Comment by Jinghao-Chen** [comment]
Hi, it is possible that your network has restrictions on accessing Docker hub.

**Comment by sarahshuang** [comment]
> Hi, it is possible that your network has restrictions on accessing Docker hub.

I see. Does it have other approaches to build SAW successfully?

**Comment by Jinghao-Chen** [comment]
> > Hi, it is possible that your network has restrictions on accessing Docker hub.
> 
> I see. Does it have other approaches to build SAW successfully?

Hi, could I ask if you need to analyze proteomics data? If you only need to analyze Stereo-seq transcriptome data, we recommend that you could use the latest SAW v8, which only need to be unzipped to use.

https://www.stomics.tech/products/BioinfoTools/OfflineSoftware
https://en.stomics.tech/products/BioinfoTools/OfflineSoftware

**Comment by sarahshuang** [comment]
> > > Hi, it is possible that your network has restrictions on accessing Docker hub.
> > 
> > 
> > I see. Does it have other approaches to build SAW successfully?
> 
> Hi, could I ask if you need to analyze proteomics data? If you only need to analyze Stereo-seq transcriptome data, we recommend that you could use the latest SAW v8, which only need to be unzipped to use.
> 
> https://www.stomics.tech/products/BioinfoTools/OfflineSoftware https://en.stomics.tech/products/BioinfoTools/OfflineSoftware

I only analyze transcriptome data. Great! I will try. Thank you!

**Comment by sarahshuang** [comment]
> > > Hi, it is possible that your network has restrictions on accessing Docker hub.
> > 
> > 
> > I see. Does it have other approaches to build SAW successfully?
> 
> Hi, could I ask if you need to analyze proteomics data? If you only need to analyze Stereo-seq transcriptome data, we recommend that you could use the latest SAW v8, which only need to be unzipped to use.
> 
> https://www.stomics.tech/products/BioinfoTools/OfflineSoftware https://en.stomics.tech/products/BioinfoTools/OfflineSoftware

Hi,

I have a new question. I am running SAW v8 with your public demo data [C04138G3_v8.0_mouse_brain_Stereo seq_N_FFPE], but I only get <tissue.gef> after running `saw count`. Why doesn't it have <.cellbin.gef> as well?

**Comment by Jinghao-Chen** [comment]
@sarahshuang Yes, in the current v8.0 version, automatic cell segmentation will not be performed for **H&E stained images of FFPE samples**. In this case, it is recommended that users use third-party tools for cell segmentation and then import the result into SAW for cellbin analysis.

**Comment by Jinghao-Chen** [comment]
@sarahshuang Yes, in the current v8.0 version, automatic cell segmentation will not be performed for **H&E stained images of FFPE samples**. In this case, it is recommended that users use third-party tools for cell segmentation and then import the result into SAW for cellbin analysis.

**Comment by sarahshuang** [comment]
> @sarahshuang Yes, in the current v8.0 version, automatic cell segmentation will not be performed for **H&E stained images of FFPE samples**. In this case, it is recommended that users use third-party tools for cell segmentation and then import the result into SAW for cellbin analysis.

Got it. Thank you!
