### ISSUE TITLE
About StereoMap & Image Studio V3.0

### ISSUE THREAD

**Issue by sarahshuang** [STOmics/SAW#139]
Hi,

I am utilizing <StereoMap & Image Studio V3.0> on clouds with C02533C1.cellbin.gef. After changing the counts and its cluster results and save to a new .gef file, I found there is no change to the visulization. I am wondering how this platform can read and show the cluster result of the file. 

The code I used: `stereo.io.update_gef(data, gef_file='./newC02533C1.cellbin.gef', cluster_res_key='leiden')
`

Best,
Shuang

**Comment by Jinghao-Chen** [comment]
@sarahshuang Hi, StereoMap read the information in cellbin.gef['codedCellBlock']. The information is written by SAW, so after running `stereo.io.update_gef()`, it is necessary to run `SAW cellChunk -i cellbin.gef -o output_dir`

**Comment by sarahshuang** [comment]
> @sarahshuang Hi, StereoMap read the information in cellbin.gef['codedCellBlock']. The information is written by SAW, so after running `stereo.io.update_gef()`, it is necessary to run `SAW cellChunk -i cellbin.gef -o output_dir`

Ah, it seems that there is no `cellChunk` module for SAW 8.0.1.

Actually, I think I am encountered with a more complex case. First, I had problems in downloading saw v7.0 and other previous versions, so I turned to use your demo data for v8.0, because I only successfully installed saw v8.0.1. However, I found v8.0 cannot get the cellbin result. Then, I thought I need to try Mousekidney(v7.0) again hahahah, so I process the data <.cellbin.gef>, run `stereo.io.update_gef()` and visulize via your online platform.

**Comment by Jinghao-Chen** [comment]
@sarahshuang Hi, for SAW 8.0.1, you could try the following code:
`/path/to/your/saw-8.0.1/anaconda/bin/python /path/to/your/saw-8.0.1/lib/cellshape/cellShape.pyc -i /path/to/your/cellbin.gef -o output_dir`

**Comment by sarahshuang** [comment]
> @sarahshuang Hi, for SAW 8.0.1, you could try the following code: `/path/to/your/saw-8.0.1/anaconda/bin/python /path/to/your/saw-8.0.1/lib/cellshape/cellShape.pyc -i /path/to/your/cellbin.gef -o output_dir`

Thanks for your kind help! It finally works. =]
