### ISSUE TITLE
SAW-A40004:    IPR "ssDNA/QCInfo" attribute "QCPassFlag" is less than 1.

### ISSUE THREAD

**Issue by Druidzha** [STOmics/SAW#153]
I got an issue ,
 error code:SAW-A40004:    IPR "ssDNA/QCInfo" attribute "QCPassFlag" is less than 1.
log_tissuecut:Error in rule tissuecut:
    jobid: 0
    input: /share/home/1/1/raw_data/stereo_seq/saw/run/Toad_Gland/STEREO_ANALYSIS_WORKFLOW_PROCESSING/ALIGNMENT/D03254G212.merge.barcodeReadsCount.txt, /share/home/1/1/raw_data/stereo_seq/saw/run/Toad_Gland/STEREO_ANALYSIS_WORKFLOW_PROCESSING/IMAGE/flag
    output: /share/home/1/1/raw_data/stereo_seq/saw/run/Toad_Gland/STEREO_ANALYSIS_WORKFLOW_PROCESSING/EXPRESSION_MATRIX/tissuecut.stat, /share/home/1/1/raw_data/stereo_seq/saw/run/Toad_Gland/STEREO_ANALYSIS_WORKFLOW_PROCESSING/EXPRESSION_MATRIX/D03254G212.tissue.gef, /share/home/1/1/raw_data/stereo_seq/saw/run/Toad_Gland/STEREO_ANALYSIS_WORKFLOW_PROCESSING/EXPRESSION_MATRIX/tissue_fig
    log: /share/home/1/1/raw_data/stereo_seq/saw/run/Toad_Gland/STEREO_ANALYSIS_WORKFLOW_PROCESSING/EXPRESSION_MATRIX/log_tissuecut (check log file(s) for error details)

SystemExit in file /share/home/lvbin/software/saw-8.0.2/config/base.smk, line 416:
Exit Snakemake program: The command Error: python /share/home/lvbin/software/saw-8.0.2/lib/saw_tissuecut/Tissuecut.pyc -i /share/home/1/1/raw_data/stereo_seq/saw/run/Toad_Gland/STEREO_ANALYSIS_WORKFLOW_PROCESSING/ANNOTATION/D03254G212.raw.gef -o /share/home/1/1/raw_data/stereo_seq/saw/run/Toad_Gland/STEREO_ANALYSIS_WORKFLOW_PROCESSING/EXPRESSION_MATRIX --dnbfile /share/home/1/1/raw_data/stereo_seq/saw/run/Toad_Gland/STEREO_ANALYSIS_WORKFLOW_PROCESSING/ALIGNMENT/D03254G212.merge.barcodeReadsCount.txt  --sn D03254G212 -O Transcriptomics -d -t 10 >/share/home/1/1g/raw_data/stereo_seq/saw/run/Toad_Gland/STEREO_ANALYSIS_WORKFLOW_PROCESSING/EXPRESSION_MATRIX/log_tissuecut 2>&1 failed to execute.
Error message: 
  File "/share/home/1/software/saw-8.0.2/anaconda/lib/python3.8/concurrent/futures/thread.py", line 57, in run
  File "/share/home/1/software/saw-8.0.2/config/base.smk", line 416, in __rule_tissuecut
  File "/share/home/1/software/saw-8.0.2/config/util.py", line 23, in run_command
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: .snakemake/log/2024-09-26T221455.731515.snakemake.log

Thanks a lot!!!!

**Comment by Jinghao-Chen** [comment]
Hi, because it seems that your image did not pass ImageQC. Please refer to https://www.stomics.tech/service/new-saw-operation-manual.html or https://en.stomics.tech/service/new-saw-operation-manual.html `Tutorials->With manually processed files` for more information

**Comment by Druidzha** [comment]
thanks a lot!
