### ISSUE TITLE
Error code:SAW-A10400

### ISSUE THREAD

**Issue by doou0** [STOmics/SAW#22]
Is the unit of the number
【 -- limitGenomeGenerateRAM a higher value (like 170000000000) 】
“B”？

If I want to use this parameter, I need to convert it to “GB” to measure the limit that my server can set.

And, (set --limitBAMsortRAM ,--limitGenomeGenerateRAM or --outBAMsortingBinsN to higher values). all these three parameters need to be set or just set the corresponding parameters according to the error report?

Any answer could help！
Thanks！

**Comment by Clouate** [comment]
Hi @doou0 
Yes, the unit of the number is "B", you need to convert it to "GB" if necessary.
Just set the corresponding parameters according to the error report. The output log of STAR may record program breakpoints and how much RAM the process need. These three parameters were advised by STAR integrated in our program (https://github.com/alexdobin/STAR).
And we advise that check the input files (file path and content). In most cases it is the cause of this error code

**Comment by doou0** [comment]
> Hi @doou0 Yes, the unit of the number is "B", you need to convert it to "GB" if necessary. Just set the corresponding parameters according to the error report. The output log of STAR may record program breakpoints and how much RAM the process need. These three parameters were advised by STAR integrated in our program (https://github.com/alexdobin/STAR). And we advise that check the input files (file path and content). In most cases it is the cause of this error code

Hi, 
According to the suggestion, we checked the input files and code, but still reported such an error. The 128 line of the code mentioned in the error report is the line mentioned in the figure. However, we do not know exactly what caused the error. We hope you can help us to figure it out. Thank you again！
<img width="808" alt="微信图片_20221125102343" src="https://user-images.githubusercontent.com/116718602/203887757-fd280987-fe1a-4c65-90e3-930d5b1dc033.png">

**Comment by Clouate** [comment]
The problem may due to unsufficient RAM of your machine, could you show your script and check your output file (00.mapping/*.Log.out) to find the step in which the process hangup?

**Comment by doou0** [comment]
> The problem may due to unsufficient RAM of your machine, could you show your script and check your output file (00.mapping/*.Log.out) to find the step in which the process hangup?

Hi,
Hello, may I know your BGI-ID number? Is it convenient to add WeChat directly or discuss this problem on the nail? We are eager to solve this problem。
Thanks agaiain!

**Comment by Clouate** [comment]
@doou0 
Of course, my Wechat is 1853476023
