### ISSUE TITLE
SAW.V4 and SAW.V5,the differences of input files .

### ISSUE THREAD

**Issue by JingGuo1997** [STOmics/SAW#32]
Hi SAW developers,
I previously obtained results using SAW_v4.1.0, but now I need to perform RNA velocity analysis, so I have to rerun the process with SAW_v5.4.0. However, I encountered a problem: in the Register pipeline, V4 requires *.tar.gz and *.json files, but V5 requires *.ipr and *.tar.gz files. What can I do in this situation?

**Comment by TheSallyGardens** [comment]
You can re-QC the image using imageQC1.1.3 to obtain tar.gz and ipr files.

**Comment by JingGuo1997** [comment]
Hello, SAW developer
  Thank you very much ，i obtained the ipr file and performed mapping by SAW_v5.4.0. But  i found that the result bam file for the same sample using v5.4.0's mapping has only 5G, while the result bam file for v4.1.0's mapping has 90G. The following are the scripts for V4 and V5, respectively.

#!/bin/bash
set -e
ulimit -n 10240 
dataDir= ./Rawdata
outDir= ./File
saw=./stereo-seq
export SINGULARITY_BIND=$dataDir,$outDir
bash stereoRun_singleLane_v4.1.0.sh \
    -m $./MASK/SS200000682TL_E4.barcodeToPos.h5 \
    -1 $dataDir/C_L01_trim_read_1.fq.gz  \
    -2 $dataDir/C_L01_trim_read_2.fq.gz  \
    -g ./STAR_SJ100 \
    -a ./genes/*.gtf \
    -o $outDir/result \
    -i ./image/C \
    -s $saw/SAW_v4.1.0.sif \
    -t 20 \
    -c 3.0 \
wait
exit
the results：
99G     ./00.mapping
1.3G    ./01.merge
50G     ./02.count
6.5G    ./03.register
6.0G    ./04.tissuecut
164M    ./05.spatialcluster
120K    ./06.saturation
1.1M    ./07.report
603M    ./SS200000682TL_E4_result
163G    .



#!/bin/bash
set -e
outDir= ./File
bash stereoPipeline_v5.4.0.sh   \
    -genomeSize 3.0 \
    -splitCount  1  \
    -maskFile  ./MASK/SS200000682TL_E4.barcodeToPos.h5 \
    -fq1  ./Rawdata/C_L01_trim_read_1.fq.gz \
    -fq2 ./Rawdata/C_L01_trim_read_2.fq.gz \
    -refIndex ./STAR_SJ100 \
    -speciesName h \
    -tissueType e \
    -annotationFile  ./genes/*.gtf \
    -threads  10   \
    -sif  ./stereo-seq/SAW_v5.4.0.sif  \
    -outDir  $outDir    \
    -imageRecordFile ./*.ipr     \
    -imageCompressedFile  ./*.tar.gz   \
    -doCellBin  Y
wait
exit
the results：
5.6G    ./00.mapping
301M    ./01.merge
3.3G    ./02.count
4.4G    ./04.tissuecut
448M    ./05.spatialcluster
148K    ./06.saturation
12M     ./07.report
4.0K    ./visualization
4.1G    ./03.register
39M     ./041.cellcut
67M     ./051.cellcluster
18G     .

**Comment by JingGuo1997** [comment]
> Hello, SAW developer Thank you very much ，i obtained the ipr file and performed mapping by SAW_v5.4.0. But i found that the result bam file for the same sample using v5.4.0's mapping has only 5G, while the result bam file for v4.1.0's mapping has 90G. The following are the scripts for V4 and V5, respectively.
> 
> #!/bin/bash set -e ulimit -n 10240 dataDir= ./Rawdata outDir= ./File saw=./stereo-seq export SINGULARITY_BIND=$dataDir,$outDir bash stereoRun_singleLane_v4.1.0.sh -m $./MASK/SS200000682TL_E4.barcodeToPos.h5 -1 $dataDir/C_L01_trim_read_1.fq.gz -2 $dataDir/C_L01_trim_read_2.fq.gz -g ./STAR_SJ100 -a ./genes/*.gtf -o $outDir/result -i ./image/C -s $saw/SAW_v4.1.0.sif -t 20 -c 3.0 wait exit the results： 99G ./00.mapping 1.3G ./01.merge 50G ./02.count 6.5G ./03.register 6.0G ./04.tissuecut 164M ./05.spatialcluster 120K ./06.saturation 1.1M ./07.report 603M ./SS200000682TL_E4_result 163G .
> 
> #!/bin/bash set -e outDir= ./File bash stereoPipeline_v5.4.0.sh -genomeSize 3.0 -splitCount 1 -maskFile ./MASK/SS200000682TL_E4.barcodeToPos.h5 -fq1 ./Rawdata/C_L01_trim_read_1.fq.gz -fq2 ./Rawdata/C_L01_trim_read_2.fq.gz -refIndex ./STAR_SJ100 -speciesName h -tissueType e -annotationFile ./genes/_.gtf -threads 10 -sif ./stereo-seq/SAW_v5.4.0.sif -outDir $outDir -imageRecordFile ./_.ipr -imageCompressedFile ./*.tar.gz -doCellBin Y wait exit the results： 5.6G ./00.mapping 301M ./01.merge 3.3G ./02.count 4.4G ./04.tissuecut 448M ./05.spatialcluster 148K ./06.saturation 12M ./07.report 4.0K ./visualization 4.1G ./03.register 39M ./041.cellcut 67M ./051.cellcluster 18G .


I solved this problem by upgrading to SAW5.5.2
