### ISSUE TITLE
Small example files to run SAW

### ISSUE THREAD

**Issue by vladimirkovacevic** [STOmics/SAW#35]
I want to get more familiar with the execution and steps of SAW. Can you maybe provide the dataset with small (example) FASTQ files, an image mask, and all other necessary inputs?

Thanks!

**Comment by TheSallyGardens** [comment]
Hi,you can crop fq by yourself.

**Comment by qiqiHE93** [comment]
Thank you for your interest in SAW. I recommend that you review the instructions and data provided on the following link: https://github.com/STOmics/SAW/tree/main/Test_Data. 
It's important to carefully review the instructions and data provided in the link to get familiar with the execution and steps of SAW.

Best regards!
