### ISSUE TITLE
How to get unspliced data

### ISSUE THREAD

**Issue by jadexq** [STOmics/SAW#4]
Hi, I am trying out the `test_data` using `stereoRun_singleLane_v4.1.0.sh`.  However, I failed to find the unspliced counts among the outputs. Do I need to modify `stereoRun_singleLane_v4.1.0.sh` to get the unspliced data? Thanks so much!!

**Comment by qiqiHE93** [comment]
what does that means "unspliced data" ?

**Comment by jadexq** [comment]
> 

In the Stereo-Seq paper supplementary information (on page e7) -- "Unspliced and spliced RNA for each cell were extracted from the E16.5 telencephalon with SAW." The unspliced data was then used for spatial RNA velocity analysis (Figure4 on Stereo-Seq paper page 7). Thanks so much!!

**Comment by skpalan** [comment]
Hi SAW team, I actually have the same question here. I looked through basically all the repos that BGI uploaded and cannot find an appropriate pipepline for generating spliced and unspliced RNA counts. I have tried using `kallisto` but ended up with failure to map barcodes back to cell postions. Thanks for your help in advance!

**Comment by qiqiHE93** [comment]
Hi there,

Thank you for reaching out to me regarding your question about obtaining spliced and unspliced RNA counts. 

I am glad to inform you that there is a solution that can help you obtain the unspliced and spliced RNA counts that you need. You can use the method provided in https://stereopy.readthedocs.io/en/latest/Tutorials/RNA_Velocity.html.
The tutorial outlines the steps for performing RNA velocity analysis to study expression dynamics based on scRNA-seq data. I believe it will be helpful in your situation.

Please let me know if you have any further questions or if there is anything else I can assist you with. I hope this information helps!

Best regards,

**Comment by HelloWorldLTY** [comment]
I have the same question here. How to access the gef or bgef here? I cannot find these files. It will be really helpful if you can provide the loom file for us. Thanks.

**Comment by AritaZ-hang** [comment]
lol now I meet the same situation. I hope the SAW team could add a new function to add a barcode tag or bin tag whatever(like others mentioned in another issue, CB50, CB500, indicating a mapping relationship between the bead and the spatial clusters. I've tried to find such an API in the stereopy but it seems there's no such thing) . Though coordinates could be translated into barcode names by the ST_BarcodeMap tool, it's still inconvenient to directly conduct any analysis relevant to the barcode tag.
