### ISSUE TITLE
barcodeToPos file in mouse organogenesis  data

### ISSUE THREAD

**Issue by cynthier** [STOmics/SAW#41]
Hi, thank you for your great job. The barcodeToPos.h5 files from mouse organogenesis data in MOSTA (https://db.cngb.org/stomics/mosta/download/) are relevant to the spatial position, and they are mentioned to be served as the coordinate reference of SAW pipeline. How can I get the coordinate information, like x and y of da information, using these files?  Could you please help me?

Thank you in advance!

**Comment by qiqiHE93** [comment]
Hello, thank you for reaching out. You can use the method provided in https://github.com/STOmics/ST_BarcodeMap to obtain the coordinate information you need. Please refer to the corresponding documentation and try using this method. Good luck!
