### ISSUE TITLE
Getting unmapped reads with CID and MID annotation

### ISSUE THREAD

**Issue by HenriettaHolze** [STOmics/SAW#45]
Hi, 

For my specific use case I need reads that do not map to the reference annotated with CID and MID. I am using the singularity container v6.0.1 and the SAW pipeline script v.6.0.0.  
The output bam by default only contains mapped reads.  
Could you please advise on how to obtain CID and MID for all reads in the input fastq file, not just those that map to the reference?

I added this line to the pipeline script to obtain unmapped reads from the mapping command:
        `echo "unmappedOut=${result_00mapping}/${fqbase}.unmapped.txt" >> $bcPara`
According to the help message of bcStar:
`--unmappedOut output file path for barcode unmapped reads, if this path isn't given, discard the reads. (string [=])`  
But the file is empty after running the pipeline. 

Secondly, I tried to add this line to the mapping command:
       `--outSAMunmapped Within KeepPairs \`
This results in a segmentation error during sorting. I don't know why this is happening. 
To avoid the segmentation error, I run with `--outSAMtype BAM Unsorted \`  
This results in a bam file that contains unmapped reads (flag 4) that contain the reads I need but non of them have the Cx Cy or UR flag that I needed. 

I also added this line to the mapping command
      `--outReadsUnmapped Fastx \`
The read header in the mate1 fastq file do not contain coordinate IDs either and the mate2 fastq file is empty. 

Thanks you very much for your help.

**Comment by Z-YWJ** [comment]
hi, Do you solve this problem? If so, how?

**Comment by HenriettaHolze** [comment]
Hi @Z-YWJ they introduced a parameter in v6.1 that gives a fastq file with unmapped reads. There is more information in the user manual version A7

**Comment by Z-YWJ** [comment]
Yes. I find the parameter is 'outUnMappedFq=1' set in the bcPara file. 

Thank you! 
It really help me a lot!
