### ISSUE TITLE
Report generation error

### ISSUE THREAD

**Issue by DMaspero** [STOmics/SAW#47]
Dear SAW developers,

I am trying to generate the HTML report after running SAW v6.0.1.

I am getting the following error:
`Traceback (most recent call last):
  File "report/handleReport_main.py", line 416, in <module>
  File "report/handleReport_main.py", line 363, in main
  File "report/generate_analysis_report.py", line 257, in generate_html_function
KeyError: 'x_start'
`
I think it is related to the RPI and IPR files, because if I do not specify them I can generate the report (with only _Summary_ and _Square Bins_ windows). I obtained both using _register_ tool.

I am using the following command:

singularity exec --bind /scratch_isilon:/scratch_isilon ../../../SAW_v6.0.1.sif report \
-m SN_001_barcodeMap.stat,SN_002_barcodeMap.stat, ...\
-a SN_001.Log.final.out,SN_002.Log.final.out, ... \
-g chipID.Aligned.sortedByCoord.out.merge.q10.dedup.target.bam.summary.stat \
-l tissuecut.stat \
-n raw.gef \
-b scatter_200x200_MID_gene_counts.png \
-v violin_200x200_MID_gene.png \
-c statistic_200x200_MID_gene_DNB.png \
--bin1Saturation plot_1x1_saturation.png \
--bin20Saturation scatter_20x20_MID_gene_counts.png \
--bin20violin violin_20x20_MID_gene.png \
--bin20MIDGeneDNB statistic_20x20_MID_gene_DNB.png \
--bin50Saturation scatter_50x50_MID_gene_counts.png \
--bin50violin violin_50x50_MID_gene.png \
--bin50MIDGeneDNB statistic_50x50_MID_gene_DNB.png \
--bin100Saturation scatter_100x100_MID_gene_counts.png \
--bin100violin violin_100x100_MID_gene.png \
--bin100MIDGeneDNB statistic_100x100_MID_gene_DNB.png \
--bin150Saturation scatter_150x150_MID_gene_counts.png \
--bin150violin violin_150x150_MID_gene.png \
--bin150MIDGeneDNB statistic_150x150_MID_gene_DNB.png \
-d chipID.spatial_cluster_bin100.h5ad \
-t plot_200x200_saturation.png \
-r research_version \
-s chipID \
--pipelineVersion saw_v6.0.1 \
-o ./ \
--species "specie" \
--tissue "tissue" \
--reference "specie" \
--cellBinGef chipID.cellbin.gef \
--cellCluster chipID.cell.cluster.h5ad \
--logo /opt/saw_v6.0.0_software/pipeline/report/logo.png \
-i chipID.rpi \
--rpi_resolution 100 \
--iprFile chipID_SC_20230421_114304_2.0.0.ipr \
-p /opt/saw_v6.0.0_software/pipeline/report/plotly_package.txt

Could you please, help me in figure out what could be the issue?

Thank you in advance,

Best, Davide Maspero

**Comment by TheSallyGardens** [comment]
@DMaspero Hi!
Could you provide the IPR and RPI files for us to troubleshoot?

**Comment by DMaspero** [comment]
Dear thesallygardens,

Thank you for taking care of my issue.
At these links ([​ipr icon] SS200000795TL_B5_SC_20230519_105603_2.0.0.ipr<https://crgcnag-my.sharepoint.com/:u:/g/personal/dmaspero_crg_es/EV_7IhbFxglFmHtuDL-IwEYBS1SN4FVvSMgew4_D7_BXgw?e=Xq0D6a>  and [​rpi icon]  SS200000795TL_B5.rpi<https://crgcnag-my.sharepoint.com/:u:/g/personal/dmaspero_crg_es/EemfEtl_4zZKovNZ4tVYb_kBavsXScl449ykU0rFrIZiuw?e=uCF0Hq>) you can find the two requested files.
Please, notice that they were generated using register tools from your pipeline.

Thank you again for your time and help,
Best regards,
Davide Maspero

Davide Maspero, PhD
Postdoctoral Fellow
Single Cell Genomics Team
National Centre for Genomic Analysis,
Centre for Genomic Regulation (CNAG-CRG)
Parc Científic de Barcelona – Torre I
Baldiri Reixac, 4
08028 Barcelona, Spain

**Comment by TheSallyGardens** [comment]
@DMaspero Hi!
You can try using absolute paths for rpi, which is a defect that we will fix in future versions.
Thank you for your feedback.
Best, thesallygardens

**Comment by DMaspero** [comment]
Dear @TheSallyGardens,

Your suggestion actually solved the problem. 
Thank you very much!

Best,
Davide
