### ISSUE TITLE
distance between coordinates in download data

### ISSUE THREAD

**Issue by YOU-k** [STOmics/SAW#48]
Hi who's concerning,
I am exploring a stereoseq data, and I download the file online from https://ftp.cngb.org/pub/SciRAID/stomics/STDS0000058/stomics/Mouse_olfa_S1.h5ad.
spatial coordinates are provided in the object, however I am not quite sure how do we get the coord? are they pixels? and what is the distance between any two of them? or in other words, what is the pixel size here? I would like to use micron here.
Cheers,
Chloe

**Comment by TheSallyGardens** [comment]
You can use scanpy to import h5ad, with coordinates stored in adata.obs.The distance between two DNBs is 500nm.
