### ISSUE TITLE
Unclear color legend in report 

### ISSUE THREAD

**Issue by HenriettaHolze** [STOmics/SAW#50]
Hi, 

I would like to make a small suggestion on how to improve the html report (v.6.0.0).  

In the "Square Bin" tab of the report under the Clustering section there is a tissue plot and a UMAP.  
The color legends used for these plots have repeating colors making it impossible to distinguish the clusters on the tissue plot.   
It would be great if a color palette was chosen that had more than 10 colors if more than 10 clusters are identified. 

<img width="106" alt="image" src="https://user-images.githubusercontent.com/53051882/236971685-f76c1360-10ce-4224-8541-5ea5b6657045.png">

Thanks a lot!

**Comment by TheSallyGardens** [comment]
Hi!
We suggest that you use Stereopy to re cluster.Stereopycan be more customization done.
