### ISSUE TITLE
splitCount parameter

### ISSUE THREAD

**Issue by anke-king** [STOmics/SAW#52]
I'm trying to run the stereo pipeline, however I am not sure which parameter I should use for the splitCount. I read the user manual but couldn't really find an explanation either. I am using the STT0000012: P7_MouseBrain_Sagittal_Session1.barcodeToPos.h5 mask file.

Thanks in advance, I appreciate any help!

**Comment by TheSallyGardens** [comment]
Count of splited stereochip mask file, usually 16 for SE fq data and 1 for PE fq data.

**Comment by Jinghao-Chen** [comment]
Thank you for your comment. We both agree that improving documentation is important. We will contact the author of the user manual and suggest adding more information about the splitCount parameter to the user manual. Thank you for your feedback and for helping us improve the project's documentation. Best of luck with your stereo pipeline!
