### ISSUE TITLE
Adding custom gene to reference

### ISSUE THREAD

**Issue by HenriettaHolze** [STOmics/SAW#53]
Hi, I would like to know how to add a custom gene to the reference. 

I followed the instructions from cellranger to add the sequence and annotation to the fasta and gtf file
https://support.10xgenomics.com/single-cell-gene-expression/software/pipelines/latest/using/tutorial_mr

For adding the annotation:
`echo -e 'GFP\tunknown\texon\t1\t922\t.\t+\t.\tgene_id "GFP"; transcript_id "GFP"; gene_name "GFP"; gene_biotype "protein_coding";' > GFP.gtf`
and then appended the line to my reference gtf. 

However, the gene does not appear in the raw.gef file among the gene_names when reading the gef file with stereopy. 

There are >30,000 alignments to the gene in the BAM file with flag 0 and MAPQ score 255 which should be fine. 

I was wondering how the gef file is created from the BAM file and whether I have to add another line to the annotation to obtain read counts for my gene of interest in the gef file. 

Many thanks, 
Henrietta

**Comment by Jinghao-Chen** [comment]
@HenriettaHolze Hi, would you able to find the reads in the BAM file that have your custom gene name in their annotation tags? If not, you may need to add more infomation about the custom gene to the reference gtf, including corresponding gene, transcript, and exon. 
e.g.
![a186df01c1994cc8ddd86aae67ad84a](https://github.com/STOmics/SAW/assets/58293762/3f8a0c49-d06c-4efb-9dba-0a18a9bdd459)

**Comment by HenriettaHolze** [comment]
Hi @Clouate , I followed your advice and added a line with gene, transcript and exon to the reference gtf but it did not make a difference. The gene does not appear in the raw gef. 

As mentioned above, 
There are >30,000 alignments to the gene in the BAM file with flag 0 and MAPQ score 255 which should be fine.

Do you have another idea how to trouble shoot this? Can you describe how the Bam2Gem tool generates the gene expression data?

Thanks a lot.

**Comment by Jinghao-Chen** [comment]
Hi @HenriettaHolze ,
Bam2Gem tool records the corresponding spatial position and MID into the gef file by retrieving the genes annotated according to the tag value of the effectively annotated reads.
As you described, did you find >30,000 alignments with the GE:Z: field containing the gene symbol you need?
![image](https://github.com/STOmics/SAW/assets/58293762/f6ded8ae-5af8-48cb-b3f3-3a76aae26678)

If not, could you check the number of valid genes in your different gtf files with the following command to confirm that the line you added is correct?
`singularity exec SAW.sif checkGTF -i ${input.gtf}`

**Comment by HenriettaHolze** [comment]
Hi @Clouate, 

Thanks for the response, I had not noticed that the GE flag was missing.  
I have added all flags for exon, transcript and gene that are present for other genes (not just the ones in the 10X tutorial) and now it worked. 
```
MLLAF9  unknown gene    1       8015    .       +       .       gene_id "MLLAF9"; gene_version "1"; gene_name "MLLAF9"; gene_source "unknown"; gene_biotype "protein_coding";
MLLAF9  unknown transcript      1       8015    .       +       .       gene_id "MLLAF9"; gene_version "1"; transcript_id "MLLAF9"; transcript_version "1"; gene_name "MLLAF9"; gene_source "unknown"; gene_biotype "protein_coding"; transcript_name "MLLAF9"; transcript_source "unknown"; transcript_biotype "protein_coding";
MLLAF9  unknown exon    1       8015    .       +       .       gene_id "MLLAF9"; gene_version "1"; transcript_id "MLLAF9"; transcript_version "1"; exon_number "1"; gene_name "MLLAF9"; gene_source "unknown"; gene_biotype "protein_coding"; transcript_name "MLLAF9"; transcript_source "unknown"; transcript_biotype "protein_coding"; exon_id "MLLAF9"; exon_version "1";
```

Best, Henrietta
