### ISSUE TITLE
Mapped reads all annotated to INTERGENIC

### ISSUE THREAD

**Issue by duchen-whu** [STOmics/SAW#55]
In 02.count directory, the Aligned.sortedByCoord.out.merge.q10.dedup.target.bam.summary.stat file shows all mapped reads annotated to intergenic region, but I checked the reads many were in exon region, I want to know what's wrong with that?

Thanks!

**Comment by Jinghao-Chen** [comment]
Hi @duchen-whu 
Perhaps the chromosome name prefix in the gtf file is inconsistent with the fasta file. For example, the name is chr21 in gtf, and in fasta it is 21. Additionally,the code  below could be used to check if the gtf format is correct.
`singularity exec SAW.sif checkGTF -i ${input.gtf}`

**Comment by duchen-whu** [comment]
Thanks for your response!
I have checked the chromosome name in gtf and fasta, it's same between two files, run checkGTF is also OK.

```
> 2023-06-24 08:50:38.346 I gtf: read     100000 valid GTF records. Last read position: Chr01:109654225
> 2023-06-24 08:50:38.619 I process: loadGTFFile time(s):2
> 2023-06-24 08:50:38.901 I process: makeOverlapDetector time(s):0
> 2023-06-24 08:50:38.901 I process: Gene count:94170
> 2023-06-24 08:50:38.982 I process: checkGTF done. Elapsed time(s):2
```
