### ISSUE TITLE
How to read the results of SAW into seurat

### ISSUE THREAD

**Issue by zhongll19** [STOmics/SAW#56]
I want to use seurat to analyze stereo-seq data, but I couldn't find the correct way to read the data.
Any help would be greatly appreciated. Thanks!

**Comment by TheSallyGardens** [comment]
You can use stereopy（https://stereopy.readthedocs.io/en/latest/Tutorials/Format_Conversion.html）.

**Comment by BioRB** [comment]
Hello Developers,
we used the conversion pipe but in the end we have an empty image slot in the seurat object. We tried using:
```
st.obj <- CreateStaffliObject('image.tif', data@meta.data)
st.obj <- LoadImages(st.obj, verbose = TRUE)

```
but it rises a waring saying that sample column is missing in CreateStaffliObject. 
What this column represents. I can add it to the metadata if I can retrieve it from the output of the pipe SAW. 
I think the solution could be in the SAW register output ( tiff image and ipr), but it's just an idea. 
As we are used to seurat processing of spatial data we know that image is required to match expression spots to proper spatial locations. Thus, we expect to have the same slots in the seuratobject after the conversion. 
We see that with the pipe SAW the image is used in the step register but also that the segmentation step can be performed with or without image (https://stereopy.readthedocs.io/en/latest/Tutorials/Tissue_Segmentation.html).
Can you explain me this point?
The image is 'essential' in the stereoseq analysis and alos, we can find the image inside the gef file as we do with seurat or not?

thanks for your reply
