### ISSUE TITLE
Inconsistent names in help message from mapping

### ISSUE THREAD

**Issue by ChangqingW** [STOmics/SAW#57]
With the latest image `docker://stomics/saw:06.1.0`, `mapping` prints a help message that refers to a program `bcSTAR` that does not exist in the image:
```
Singularity> mapping
Usage: STAR  [options]... --genomeDir REFERENCE   --readFilesIn R1.fq R2.fq
Spliced Transcripts Alignment to a Reference (c) Alexander Dobin, 2009-2019

For more details see:
<https://github.com/alexdobin/STAR>
<https://github.com/alexdobin/STAR/blob/master/doc/STARmanual.pdf>

To list all parameters, run bcSTAR --help . To list STOmics parameters, run bcSTAR --helpBcPara
Singularity> bcSTAR
bash: bcSTAR: command not found
```
Consider creating an alias in the image `alias bcSTAR="mapping"` or updating the help message.

**Comment by TheSallyGardens** [comment]
You need to import bcSTAR(/opt/saw_v6.1.0_software/pipeline/mapping/bcSTAR) into the environment variable.

**Comment by ChangqingW** [comment]
> You need to import bcSTAR(/opt/saw_v6.1.0_software/pipeline/mapping/bcSTAR) into the environment variable.

Yes, but since `mapping` redirects to `bcSTAR`
```
Singularity> cat $(which mapping)
/opt/saw_v6.1.0_software/pipeline/mapping/bcSTAR $*
```
It is confusing for users to see `mapping --help` referring to `bcSTAR`, but `bcSTAR` is not available by default. I don't think this is mention in the user manual either?
