### ISSUE TITLE
error in lasso function

### ISSUE THREAD

**Issue by HenriettaHolze** [STOmics/SAW#58]
Hi, 
I'm trying to manually segment a tissue section but got an error from the lasso function in SAW. 

I first ran SAW v6.1.0 using the provided pipeline script.  
Then I used the lasso function in StereoMap v.2.0.0 with the 04.tissuecut/{SN}.gef to cut out the section of interest and saved it as .geojson. 
Then I ran SAW v6.1.0 with following command as described in the SAW manual: 

```
mkdir -p ${project_dir}/preprocessed_data/saw_output/mouse2_spleen/lasso/
singularity exec ${project_dir}/SAW_06.1.0.sif lasso \
    -i ${project_dir}/preprocessed_data/saw_output/mouse2_spleen/04.tissuecut/SS200000334TR_A2.gef \
    -m ${project_dir}/preprocessed_data/StereoMapOutput/20230727144034.whole_tissue_mouse2_lasso.geojson \
    -o ${project_dir}/preprocessed_data/saw_output/mouse2_spleen/lasso/ \
    -s 10 \
    -n SS200000334TR_A2
```
And got following error:

```
2023-07-27 15:34:36,689 - root - batch count is 3980021
2023-07-27 15:35:08,892 - root - Reading data..
/usr/local/python3/lib/python3.8/site-packages/gefpy/cell_mask_annotation.py:62: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  uID_label_df = uID_label_df.append({'uID':uID, 'label':label}, ignore_index=True)
Traceback (most recent call last):
  File "lasso/cell_mask_lasso_v1.1.1.py", line 79, in <module>
  File "lasso/cell_mask_lasso_v1.1.1.py", line 76, in main
  File "/usr/local/python3/lib/python3.8/site-packages/gefpy/cell_mask_annotation.py", line 177, in run_cellMask
    self.SplitProcess()
  File "/usr/local/python3/lib/python3.8/site-packages/gefpy/cell_mask_annotation.py", line 108, in SplitProcess
    self.maskFile, self.uID_label_df = self.readMaskFile(self.infile)
  File "/usr/local/python3/lib/python3.8/site-packages/gefpy/cell_mask_annotation.py", line 32, in readMaskFile
    maskFile, uID_label_df = self.read_Geojson(infile)
  File "/usr/local/python3/lib/python3.8/site-packages/gefpy/cell_mask_annotation.py", line 63, in read_Geojson
    cv2.fillPoly(mask, areas, uID)
cv2.error: OpenCV(4.5.4) /tmp/pip-req-build-khv2fx3p/opencv/modules/imgproc/src/drawing.cpp:2395: error: (-215:Assertion failed) p.checkVector(2, CV_32S) >= 0 in function 'fillPoly'
```

If I am using a deprecated version of StereoMap, could you please point me to where to download the most recent version? Thank you.

**Comment by TheSallyGardens** [comment]
You could download StereoMap from the official website at https://www.stomics.tech/products/BioinfoTools/OfflineSoftware

Best

**Comment by HenriettaHolze** [comment]
Dear @TheSallyGardens I am using StereoMap v2.0.0 and the version available under the link is v2.0.3. Since this is only a revision, there should be no difference in the output formats generated by the versions. 

Do you have another idea how this error could happen? 

Best

**Comment by TheSallyGardens** [comment]
@HenriettaHolze  Hi~
The latest version on the official website is V2.1.
https://cdn-newfile.stomics.tech/StereoMap_2.1.0.zip

**Comment by HenriettaHolze** [comment]
Sorry, on the english page I could only find 2.0.3 https://en.stomics.tech/BioinfoTools

Thanks for sending the direct link, unfortunately it is blocked by the firewall of my institute. 
I am struggling to register at the chinese BGI website because my phone number is not accepted. Could you upload the software somewhere else where I can access it? 
Thanks!

**Comment by TheSallyGardens** [comment]
@HenriettaHolze Hi~
We are very sorry that our staff will update the English version of the official website download link next Monday.

Best
