### ISSUE TITLE
KeyError: "Unable to open object (object 'TemplatePoint' doesn't exist)"

### ISSUE THREAD

**Issue by OnkarMulay** [STOmics/SAW#63]
version: Latest SAW - 6.1

[INFO 20230810-10-53-32 p3618007 run main.py:246] >> Next do the stitching task.
I0810 10:53:32.176671 3618007 main.py:246] >> Next do the stitching task.
[INFO 20230810-10-53-32 p3618007 deploy_imgs fov_info.py:88] Get imgs from /scratch/project/stseq/Onkar/STOmics/stomics_cell_segment/Outputs/SAW3//03.register/ssDNA/SS200000122TL_D1.
I0810 10:53:32.184700 3618007 fov_info.py:88] Get imgs from /scratch/project/stseq/Onkar/STOmics/stomics_cell_segment/Outputs/SAW3//03.register/ssDNA/SS200000122TL_D1.
[INFO 20230810-10-53-32 p3618007 __init__ fov_info.py:72] 99 motic-FOV arrangement in 11 X 9 grid, as shape is 2035 X 2436.
I0810 10:53:32.226236 3618007 fov_info.py:72] 99 motic-FOV arrangement in 11 X 9 grid, as shape is 2035 X 2436.
[INFO 20230810-10-53-32 p3618007 save_mosaic fov_stitch.py:115] Stitched image shape is (20355, 19980), saving will take some times.
I0810 10:53:32.229992 3618007 fov_stitch.py:115] Stitched image shape is (20355, 19980), saving will take some times.
[INFO 20230810-10-53-35 p3618007 save_mosaic fov_stitch.py:173] Eval stitch image - tissue, please wait.
I0810 10:53:35.856606 3618007 fov_stitch.py:173] Eval stitch image - tissue, please wait.
[INFO 20230810-10-54-37 p3618007 register_fine_tuning fov_stitch.py:244] Fov Transform.
I0810 10:54:37.187599 3618007 fov_stitch.py:244] Fov Transform.
Traceback (most recent call last):
  File "register/stereo-resep-cell_v3.3.4/stereo-resep/main.py", line 879, in <module>
  File "register/stereo-resep-cell_v3.3.4/stereo-resep/main.py", line 37, in __init__
  File "register/stereo-resep-cell_v3.3.4/stereo-resep/main.py", line 122, in pipeline_entry
  File "register/stereo-resep-cell_v3.3.4/stereo-resep/main.py", line 296, in run
  File "register/stereo-resep-cell_v3.3.4/stereo-resep/stitching/stitch.py", line 28, in stitch_entry
  File "register/stereo-resep-cell_v3.3.4/stereo-resep/stitching/fov_stitching/fov_stitch.py", line 546, in stitching
  File "register/stereo-resep-cell_v3.3.4/stereo-resep/stitching/fov_stitching/fov_stitch.py", line 208, in save_mosaic
  File "register/stereo-resep-cell_v3.3.4/stereo-resep/stitching/fov_stitching/fov_stitch.py", line 292, in standard_based_calibration_image
  File "register/stereo-resep-cell_v3.3.4/stereo-resep/stitching/fov_stitching/fov_stitch.py", line 245, in register_fine_tuning
  File "register/stereo-resep-cell_v3.3.4/stereo-resep/utils/common.py", line 365, in deduce_splice_template
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/usr/local/python3/lib/python3.8/site-packages/h5py/_hl/group.py", line 328, in __getitem__
    oid = h5o.open(self.id, self._e(name), lapl=self._lapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5o.pyx", line 190, in h5py.h5o.open

An error at stitching step? Any suggestion on how can I fix this?

Thanks for the SAW tool.
Regards,
Onkar

**Comment by Jinghao-Chen** [comment]
If you are running the register step separately, please make sure you have executed the following code first. Additionally, SAW 6.1 is compatible with ImageStudio 2.* versions, and it is recommended to use the latest version of ImageStudio for image quality control.
`export HDF5_USE_FILE_LOCKING=FALSE`

**Comment by OnkarMulay** [comment]
Thanks for help and suggestion @Clouate. 
I am using SAW 6.1 and ImageStudio-2.1 
I will add the above command to my shell script. Thanks for the help. I will close this issue if job is successful or may update with the error.

Regards,
Onkar

**Comment by OnkarMulay** [comment]
@Clouate, the solution doesn't work. and this command I can also see being used across the script. Is there any other solution?

**Comment by Jinghao-Chen** [comment]
It seems that the stitching step did not complete successfully. If possible, could you upload the complete running log? Alternatively, you could use the stitched image generated by microscope for ImageStudio: QC and SAW analysis.

**Comment by OnkarMulay** [comment]
WARNING: SINGULARITY_BIND and APPTAINER_BIND have different values, using the latter
        Command being timed: "singularity exec /QRISdata/Q5058/sMACS/STomics/Raw/SAW/SAW_sif/SAW_6.1.sif CIDCount -i /scratch/project/stseq/Onkar/STOmics/stomics_cell_segment/brain/Y4/01.Filter/SS200000122TL_D1.barcodeToPos.h5 -s mouse -g 5"
        User time (seconds): 20.53
        System time (seconds): 1.22
        Percent of CPU this job got: 60%
        Elapsed (wall clock) time (h:mm:ss or m:ss): 0:36.03
        Average shared text size (kbytes): 0
        Average unshared data size (kbytes): 0
        Average stack size (kbytes): 0
        Average total size (kbytes): 0
        Maximum resident set size (kbytes): 709804
        Average resident set size (kbytes): 0
        Major (requiring I/O) page faults: 144
        Minor (reclaiming a frame) page faults: 475279
        Voluntary context switches: 276575
        Involuntary context switches: 36
        Swaps: 0
        File system inputs: 33976
        File system outputs: 0
        Socket messages sent: 0
        Socket messages received: 0
        Signals delivered: 0
        Page size (bytes): 4096
        Exit status: 0
WARNING: SINGULARITY_BIND and APPTAINER_BIND have different values, using the latter
        Command being timed: "singularity exec /QRISdata/Q5058/sMACS/STomics/Raw/SAW/SAW_sif/SAW_6.1.sif mapping --outSAMattributes spatial --outSAMtype BAM SortedByCoordinate --genomeDir /scratch/project/stseq/Onkar/STOmics/stomics_cell_segment/NEW_STAR_SJ100 --runThreadN 96 --outFileNamePrefix /scratch/project/stseq/Onkar/STOmics/stomics_cell_segment/Outputs/brain_Y4//00.mapping/DP8400025872TR_L01_read_1. --sysShell /bin/bash --stParaFile /scratch/project/stseq/Onkar/STOmics/stomics_cell_segment/Outputs/brain_Y4//00.mapping/DP8400025872TR_L01_read_1.bcPara --readNameSeparator " " --limitBAMsortRAM 63168332971 --limitOutSJcollapsed 10000000 --limitIObufferSize=280000000 --outBAMsortingBinsN 50"
        User time (seconds): 72247.24
        System time (seconds): 1228.00
        Percent of CPU this job got: 1116%
        Elapsed (wall clock) time (h:mm:ss or m:ss): 1:49:38
        Average shared text size (kbytes): 0
        Average unshared data size (kbytes): 0
        Average stack size (kbytes): 0
        Average total size (kbytes): 0
        Maximum resident set size (kbytes): 146578128
        Average resident set size (kbytes): 0
        Major (requiring I/O) page faults: 171
        Minor (reclaiming a frame) page faults: 328336930
        Voluntary context switches: 4819908
        Involuntary context switches: 183700
        Swaps: 0
        File system inputs: 29024
        File system outputs: 0
        Socket messages sent: 0
        Socket messages received: 0
        Signals delivered: 0
        Page size (bytes): 4096
        Exit status: 0
WARNING: SINGULARITY_BIND and APPTAINER_BIND have different values, using the latter
        Command being timed: "singularity exec /QRISdata/Q5058/sMACS/STomics/Raw/SAW/SAW_sif/SAW_6.1.sif count -i /scratch/project/stseq/Onkar/STOmics/stomics_cell_segment/Outputs/brain_Y4//00.mapping/DP8400025872TR_L01_read_1.Aligned.sortedByCoord.out.bam -o /scratch/project/stseq/Onkar/STOmics/stomics_cell_segment/Outputs/brain_Y4//02.count/SS200000122TL_D1.Aligned.sortedByCoord.out.merge.q10.dedup.target.bam -a /scratch/project/stseq/Onkar/STOmics/stomics_cell_segment/Mouse_reference_v5/mouse/genes/Mus_musculus.GRCm39.107.gtf -s /scratch/project/stseq/Onkar/STOmics/stomics_cell_segment/Outputs/brain_Y4//02.count/SS200000122TL_D1.Aligned.sortedByCoord.out.merge.q10.dedup.target.bam.summary.stat -e /scratch/project/stseq/Onkar/STOmics/stomics_cell_segment/Outputs/brain_Y4//02.count/SS200000122TL_D1.raw.gef --sat_file /scratch/project/stseq/Onkar/STOmics/stomics_cell_segment/Outputs/brain_Y4//02.count/SS200000122TL_D1_raw_barcode_gene_exp.txt --umi_on --umi_len 10 --save_lq --save_dup --sn SS200000122TL_D1 -c 96 -m 128"
        User time (seconds): 14197.17
        System time (seconds): 732.65
        Percent of CPU this job got: 1554%
        Elapsed (wall clock) time (h:mm:ss or m:ss): 16:00.32
        Average shared text size (kbytes): 0
        Average unshared data size (kbytes): 0
        Average stack size (kbytes): 0
        Average total size (kbytes): 0
        Maximum resident set size (kbytes): 134749416
        Average resident set size (kbytes): 0
        Major (requiring I/O) page faults: 245
        Minor (reclaiming a frame) page faults: 135447688
        Voluntary context switches: 44010980
        Involuntary context switches: 172196
        Swaps: 0
        File system inputs: 47056
        File system outputs: 0
        Socket messages sent: 0
        Socket messages received: 0
        Signals delivered: 0
        Page size (bytes): 4096
        Exit status: 0
WARNING: SINGULARITY_BIND and APPTAINER_BIND have different values, using the latter
I0831 18:43:53.513263 2272128 utils.py:142] Note: detected 192 virtual cores but NumExpr set to maximum of 64, check "NUMEXPR_MAX_THREADS" environment variable.
I0831 18:43:53.513387 2272128 utils.py:145] Note: NumExpr detected 192 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
I0831 18:43:53.513430 2272128 utils.py:157] NumExpr defaulting to 8 threads.
I0831 18:43:58.915585 2272128 schemas.py:1221] Resource 'XMLSchema.xsd' is already loaded
2023-08-31 18:44:16.406023: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/python3/lib/python3.8/site-packages/cv2/../../lib64:/opt/lib:/.singularity.d/libs
2023-08-31 18:44:16.406124: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
[INFO 20230831-18-44-24 p2272128 prepare_dir main.py:473] Dir preparation completed.
I0831 18:44:24.506735 2272128 main.py:473] Dir preparation completed.
[WARN 20230831-18-44-24 p2272128 check_files2 main.py:497] The *_transformed.tif image could not be found under the /scratch/project/stseq/Onkar/STOmics/stomics_cell_segment/brain/Y4/BGI_Brain_Y4_SS200000112TL_D1_stitch_corrected/SS200000122TL_D1_SC_20230727_134924_2.1.0.tar.gz.
W0831 18:44:24.507096 2272128 main.py:497] The *_transformed.tif image could not be found under the /scratch/project/stseq/Onkar/STOmics/stomics_cell_segment/brain/Y4/BGI_Brain_Y4_SS200000112TL_D1_stitch_corrected/SS200000122TL_D1_SC_20230727_134924_2.1.0.tar.gz.
[INFO 20230831-18-44-24 p2272128 prepare_input main.py:524] Original data already exists, skip input preparation.
I0831 18:44:24.509404 2272128 main.py:524] Original data already exists, skip input preparation.
[INFO 20230831-18-44-24 p2272128 pipeline_entry main.py:93] Copy ipr.
I0831 18:44:24.513353 2272128 main.py:93] Copy ipr.
[WARN 20230831-18-44-24 p2272128 run main.py:197] Pipeline need to handle these subtask: ['cellseg', 'register', 'stitch', 'tissueseg'].
W0831 18:44:24.519153 2272128 main.py:197] Pipeline need to handle these subtask: ['cellseg', 'register', 'stitch', 'tissueseg'].
[INFO 20230831-18-44-24 p2272128 run main.py:246] >> Next do the stitching task.
I0831 18:44:24.519503 2272128 main.py:246] >> Next do the stitching task.
[INFO 20230831-18-44-24 p2272128 deploy_imgs fov_info.py:88] Get imgs from /scratch/project/stseq/Onkar/STOmics/stomics_cell_segment/Outputs/brain_Y4//03.register/ssDNA/SS200000122TL_D1.
I0831 18:44:24.526889 2272128 fov_info.py:88] Get imgs from /scratch/project/stseq/Onkar/STOmics/stomics_cell_segment/Outputs/brain_Y4//03.register/ssDNA/SS200000122TL_D1.
[INFO 20230831-18-44-24 p2272128 __init__ fov_info.py:72] 99 motic-FOV arrangement in 11 X 9 grid, as shape is 2035 X 2436.
I0831 18:44:24.582491 2272128 fov_info.py:72] 99 motic-FOV arrangement in 11 X 9 grid, as shape is 2035 X 2436.
[INFO 20230831-18-44-24 p2272128 save_mosaic fov_stitch.py:115] Stitched image shape is (20355, 19980), saving will take some times.
I0831 18:44:24.584720 2272128 fov_stitch.py:115] Stitched image shape is (20355, 19980), saving will take some times.
[INFO 20230831-18-44-29 p2272128 save_mosaic fov_stitch.py:173] Eval stitch image - tissue, please wait.
I0831 18:44:29.821589 2272128 fov_stitch.py:173] Eval stitch image - tissue, please wait.
[INFO 20230831-18-45-40 p2272128 register_fine_tuning fov_stitch.py:244] Fov Transform.
I0831 18:45:40.334409 2272128 fov_stitch.py:244] Fov Transform.
Traceback (most recent call last):
  File "register/stereo-resep-cell_v3.3.4/stereo-resep/main.py", line 879, in <module>
  File "register/stereo-resep-cell_v3.3.4/stereo-resep/main.py", line 37, in __init__
  File "register/stereo-resep-cell_v3.3.4/stereo-resep/main.py", line 122, in pipeline_entry
  File "register/stereo-resep-cell_v3.3.4/stereo-resep/main.py", line 296, in run
  File "register/stereo-resep-cell_v3.3.4/stereo-resep/stitching/stitch.py", line 28, in stitch_entry
  File "register/stereo-resep-cell_v3.3.4/stereo-resep/stitching/fov_stitching/fov_stitch.py", line 546, in stitching
  File "register/stereo-resep-cell_v3.3.4/stereo-resep/stitching/fov_stitching/fov_stitch.py", line 208, in save_mosaic
  File "register/stereo-resep-cell_v3.3.4/stereo-resep/stitching/fov_stitching/fov_stitch.py", line 292, in standard_based_calibration_image
  File "register/stereo-resep-cell_v3.3.4/stereo-resep/stitching/fov_stitching/fov_stitch.py", line 245, in register_fine_tuning
  File "register/stereo-resep-cell_v3.3.4/stereo-resep/utils/common.py", line 365, in deduce_splice_template
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/usr/local/python3/lib/python3.8/site-packages/h5py/_hl/group.py", line 328, in __getitem__
    oid = h5o.open(self.id, self._e(name), lapl=self._lapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5o.pyx", line 190, in h5py.h5o.open
KeyError: "Unable to open object (object 'TemplatePoint' doesn't exist)"
Command exited with non-zero status 1
        Command being timed: "singularity exec /QRISdata/Q5058/sMACS/STomics/Raw/SAW/SAW_sif/SAW_6.1.sif register -i /scratch/project/stseq/Onkar/STOmics/stomics_cell_segment/brain/Y4/BGI_Brain_Y4_SS200000112TL_D1_stitch_corrected/SS200000122TL_D1_SC_20230727_134924_2.1.0.tar.gz -c /scratch/project/stseq/Onkar/STOmics/stomics_cell_segment/brain/Y4/BGI_Brain_Y4_SS200000112TL_D1_stitch_corrected/SS200000122TL_D1_SC_20230728_083756_2.1.0.ipr -v /scratch/project/stseq/Onkar/STOmics/stomics_cell_segment/Outputs/brain_Y4//02.count/SS200000122TL_D1.raw.gef -o /scratch/project/stseq/Onkar/STOmics/stomics_cell_segment/Outputs/brain_Y4//03.register"
        User time (seconds): 144.91
        System time (seconds): 28.71
        Percent of CPU this job got: 144%
        Elapsed (wall clock) time (h:mm:ss or m:ss): 1:59.78
        Average shared text size (kbytes): 0
        Average unshared data size (kbytes): 0
        Average stack size (kbytes): 0
        Average total size (kbytes): 0
        Maximum resident set size (kbytes): 2104996
        Average resident set size (kbytes): 0
        Major (requiring I/O) page faults: 5307
        Minor (reclaiming a frame) page faults: 2673093
        Voluntary context switches: 134674
        Involuntary context switches: 4613468
        Swaps: 0
        File system inputs: 1473448
        File system outputs: 0
        Socket messages sent: 0
        Socket messages received: 0
        Signals delivered: 0
        Page size (bytes): 4096
        Exit status: 1

**Comment by OnkarMulay** [comment]
With the microscope fov stitched image it works but cell segmentation is not optimum. So, I wanted to use manual stitched output from ImageQC 2.1 with SAW 6.1.1 but it has templatepoint issues.

**Comment by Jinghao-Chen** [comment]
In the directory ImageStudioWorkspace/Stitch/{SN}_{date}/ at the same level as the ImageStudio installation directory, the image stitched by the software, fov_stitched.tif, was saved. It could be used for QC and SAW after confirming the stitching effect.

**Comment by OnkarMulay** [comment]
Thanks for the suggestion. I have tried it and Image QC gives very high stiching deviation and I have to run manual stitching using ImageStudio2.1 and then I run SAW6.1.

From the above error.log file - is there any suggestion that would help me to run SAW successfully?

**Comment by OnkarMulay** [comment]
Is there any update on this issue?

**Comment by Jinghao-Chen** [comment]
Stiching deviation given by Image QC could be ignored if you confirm the stitching effect after checking the image, fov_stitched.tif, which were generated after manual stitching. By the way, ImageStudio was updated to 2.2.0, you could update the software and try again

**Comment by OnkarMulay** [comment]
![image](https://github.com/STOmics/SAW/assets/47315377/6aed7793-7aab-43bc-b764-6ef0d106cf06)
If the stitching deviation is large, the SAW can't handle it. And if we fix the error in ImageStudio we have template point issue.
Can I get some help with this?

![image](https://github.com/STOmics/SAW/assets/47315377/9fc54995-780e-41a4-9dae-150b2cf9fc0e)
The signal is from outside the cell-boundary.

Our cell-segment data captures the tissue area/outline 100% correctly (which hints registration was correct - Outlined red shape). -> How could this be possible if registration went wrong? If registration is wrong then our cell-segment mask should be wrong as well isn't it?
![image](https://github.com/STOmics/SAW/assets/47315377/56ba9e0f-3cd9-4467-95ef-951ff95d9666)
image used from stereocell - paper (bioRxiv)

**Comment by Jinghao-Chen** [comment]
After you fixed the error in ImageStudio, the image, fov_stitched.tif, in the directory ImageStudioWorkspace/Stitch/{SN}_{date}/ was based on your stitching and could be used for QC and SAW. 

Tissue/Cell segmentation step was based on the image and identifed tissue/cell areas on the image itself even if the image registration was wrong. Therefore you may need to do manual registration by StereoMap.

**Comment by OnkarMulay** [comment]
Ok, then if the registration went wrong, it wouldn't affect the cellbin.h5ad file that we get, or would it affect the cellbin files in terms of genes detected per cell? -> In other words does this issue with image registration effect the registration between the transcriptional heatmap and the cellbins/cell segmentation? or is the registration step only to overlay the image with the heatmap?

Can you confirm this:
"Therefore you may need to do manual registration by StereoMap." -> and then re-run SAW with correctly registered image?

**Comment by Jinghao-Chen** [comment]
If the registration went wrong, it would affect the cellbin files, because the coordinates in the cell segmentation result generated from the image was incompatible with the transcriptional heatmap, and the next step, cellCut cgef, will filter gene expression matrix under the cell area based on the wrong coordinates in the cell segmentation result.

Not the image but a json file from StereoMap. You could consult with the FBS or refer to tutorials in the software. After you do the manual registration, a .json file will be generated by the software. You could use it and refer to SAW/Scripts/stereoPipeline_v6.1_manual_part2.sh to run 'manualRegister' and the subsequent steps.

**Comment by OnkarMulay** [comment]
Ok, I can re-run. Thanks a lot for your help. But I want to understand why some images fail to register while others don't. I want to understand some steps/processes.

![image](https://github.com/STOmics/SAW/assets/47315377/e6ff3f9c-7043-4c3d-a260-872fab2f435e)
Image-1 tissuecut on fov_transformed_image and Image-2 cell mask on fov_transformed_image. 
How did the tissuecut and cellmask take that shape? -> It was because the pipeline registers nuclei image to gene expression heatmap line 3 - Image Registration paragh (StereoCell paper).

There is no way in which we can get cellmask without the registration happening correctly somewhere in the pipeline.
And then at the last step it seems to fail to save the registration of nuclei image. 

Thanks, will be really great if you can help me in understanding this. Is this understanding correct?

**Comment by OnkarMulay** [comment]
`"cellCut cgef, will filter gene expression matrix under the cell area based on the wrong coordinates in the cell segmentation result."`
The cellbin and bin80 also seem to have overlapping coordinates. I assume that the molecule labelling step is happening based on the coordinates of cellbin data - using cell mask coordinates?

**Comment by Jinghao-Chen** [comment]
> **But I want to understand why some images fail to register while others don't. I want to understand some steps/processes.**
The registration algorithm aligns the track lines in the image with the track lines in the expression matrix. Therefore, some images with fewer track lines or poor track line clarity, or  gene expression with diffusion phenomena due to experiments or samples, may lead to registration errors.

> **How did the tissuecut and cellmask take that shape? -> It was because the pipeline registers nuclei image to gene expression heatmap line 3 - Image Registration paragh (StereoCell paper).**
Yes, the tissuecut and cellmask were generated from the image. As you can see, the tissue segmentation region size is smaller than the gene expression heatmap because the image are not registered correctly. If you correct the image through manual registration by StereoMap, the tissue/cell segmentation results will also be corrected.

> **There is no way in which we can get cellmask without the registration happening correctly somewhere in the pipeline. And then at the last step it seems to fail to save the registration of nuclei image.**
What's the error messages and the code? Did you do the manual registration in StereoMap and then ran SAW: manualRegister?

> **I assume that the molecule labelling step is happening based on the coordinates of cellbin data - using cell mask coordinates?**
Yes, if (x1,y1) was defined as a cell in cell mask image, then 'cellCut cgef' would filter gene expression matrix under the same coordinate (x1,y1) in the gene expression heatmap even if they were not actually the same area due to the registration error.
