### ISSUE TITLE
Where can I download the test data?

### ISSUE THREAD

**Issue by Feng-Zhang** [STOmics/SAW#64]
When we open the link http://116.6.21.110:8090/share/QJKAO6hGUpTPbuYH7Dvi, it is an empty folder. Is it possible to download them anyelse place?
Thank you!

**Comment by Jinghao-Chen** [comment]
Sorry, there are currently no other alternatives available. We have verified that the link can be accessed correctly with data. Please try again or access it through different network.

**Comment by Feng-Zhang** [comment]
It does have no problem. Thank you.
