### ISSUE TITLE
How is the "reads_with_dnb" value calculated?

### ISSUE THREAD

**Issue by deepcard** [STOmics/SAW#65]
Hello!
I want to know how is the "reads_with_dnb" value calculated in the mapping output? In SE sequencing mode, the CID is added to the reads name instead of in the sequence. Will the statistics of this value be different from PE? Also, does this value need to be used as an evaluation indicator of data quality? How much data quality is not bad?

**Comment by TheSallyGardens** [comment]
Hi!
The sequence of reads_with_dnb will be removed.For information on stereo-seq sequencing data, please refer to https://www.stomics.tech/resource/STOmicsTestedTissueList#showHeader
