### ISSUE TITLE
Dose the GTF file downloaded from GENOCE need to be filtered?

### ISSUE THREAD

**Issue by Li-ZhiD** [STOmics/SAW#69]
Hi,

I am attempting to process the STO data on my own, I would like to know whether the GTF downloaded from GENCODE needs to be filtered prior.

Thanks!

**Comment by TheSallyGardens** [comment]
Hello, you can use SAW checkGTF to check if the gtf meets the specifications.

Best.

**Comment by Li-ZhiD** [comment]
Thanks! I saw the script in this repository.
