### ISSUE TITLE
tissue and cell segmentation model 

### ISSUE THREAD

**Issue by MariaRosariaNucera** [STOmics/SAW#71]
Hello,
I am writing this issue to ask if it is possible to specify which models have been used for the tissue and cell segmentation steps.

Thank you
Maria

**Comment by Jinghao-Chen** [comment]
Hi, there is currently no parameter provided for specifying models in SAW, but you could refer to stereopy to use other models for image segmentation and subsequent analysis.
https://stereopy.readthedocs.io/en/latest/index.html

**Comment by MariaRosariaNucera** [comment]
> Hi, there is currently no parameter provided for specifying models in SAW, but you could refer to stereopy to use other models for image segmentation and subsequent analysis. https://stereopy.readthedocs.io/en/latest/index.html

Thank you @Clouate for your quick answer. I am aware of the models available using stereopy.
My question was not about asking how to use other models in SAW, I just wanted to know which one was the model currently used in the standard SAW workflow.
Thank you again.
Maria.

**Comment by Jinghao-Chen** [comment]
For now,
Deep Learning Model V1 for cell segmentation
Deep Learning Method for tissue segmentation

**Comment by MariaRosariaNucera** [comment]
> For now, Deep Learning Model V1 for cell segmentation Deep Learning Method for tissue segmentation

Perfect, thank you :)
