### ISSUE TITLE
A rotation function would be quite intriguing?

### ISSUE THREAD

**Issue by Li-ZhiD** [STOmics/SAW#73]
Hi,
I would like to rotate the tissue at an angle, or any angle, to aid visualization and comprehension, as the current angle of tissue in the stomics chip is not unsuitable, so having a rotation function would be quite intriguing.

Thanks!

**Comment by Jinghao-Chen** [comment]
Hi, you could use StereoMap to rotate it.

**Comment by Li-ZhiD** [comment]
Thank you!
