### ISSUE TITLE
Why can't I just use docker mount to run the command?

### ISSUE THREAD

**Issue by RADIOMUMM** [STOmics/SAW#78]
I ran the reference genome construction of SAW with the following command:

` docker run -P -v /data/storeData/ztron/Project/STOmics_test/ref/:/database stomics/saw:07.0.0 mapping -h`

Then error
‘standard_init_linux.go:190: exec user process caused "exec format error" ’

Why can't you run it directly?
My server version is configured as follows：

LSB Version:    :core-4.1-amd64:core-4.1-noarch:cxx-4.1-amd64:cxx-4.1-noarch:desktop-4.1-amd64:desktop-4.1-noarch:languages-4.1-amd64:languages-4.1-noarch:printing-4.1-amd64:printing-4.1-noarch
Distributor ID: CentOS
Description:    CentOS Linux release 7.4.1708 (Core)
Release:        7.4.1708
Codename:       Core

**Comment by TheSallyGardens** [comment]
Hi,we recommend using docker version 20.10.8 or higher.

**Comment by RADIOMUMM** [comment]
> Hi,we recommend using docker version 20.10.8 or higher.

Hi 
I ended up choosing singularity and built the SIF file with the following command.
`singularity build --tmpdir . /tmp . /SAW_7.0.sif docker-archive:///data/storeData/ztron/Project/STOmics_test/img/stomics_saw_07_0_0.tar`
In the meantime my docker has been upgraded to the latest version（24.0.7）

However, the error still occurs when you finally use the following command
`singularity exec "/data/storeData/ztron/Project/STOmics_test/SAW_7.0.sif" mapping --help`
The error is as follows:
/opt/saw_v7.0.0_software/pipeline/mapping/bcSTAR: error while loading shared libraries: libnuma.so.1: cannot open shared object file: No such file or directory

Can you help me? Thank you very much.
best!

**Comment by TheSallyGardens** [comment]
@RADIOMUMM Hi, you can be updated to SAW v7.0.1 to resolve it.
Best wish!

**Comment by myshu2017-03-14** [comment]
> @RADIOMUMM Hi, you can be updated to SAW v7.0.1 to resolve it. Best wish!

Hi, I updated to SAW v7.0.1. But the error is still there.

>/opt/saw_v7.0.0_software/pipeline/mapping/bcSTAR: error while loading shared libraries: libnuma.so.1: cannot open shared object file: No such file or directory

**Comment by RADIOMUMM** [comment]
> > @RADIOMUMM Hi, you can be updated to SAW v7.0.1 to resolve it. Best wish!
> 
> Hi, I updated to SAW v7.0.1. But the error is still there.
> 
> > /opt/saw_v7.0.0_software/pipeline/mapping/bcSTAR: error while loading shared libraries: libnuma.so.1: cannot open shared object file: No such file or directory

You need to go into the container and create a soft connection to libnuma.so.1.
