### ISSUE TITLE
register KeyError: "Can't open attribute (can't locate attribute: 'WhichStitch')"

### ISSUE THREAD

**Issue by iichelhadi** [STOmics/SAW#79]
Hi guys,

I am trying to run your pipeline (v7.0) on the olfactory test data. When I reach the part of "# Run SAW register to stitch microscope tile images into a panoramic image..." of the script and try running the command of register
```   
singularity exec ${sif} register \
        -i ${imageTarFile} \
        -c ${iprFile} \
        -v ${outDir}/02.count/${SN}.raw.gef \
        -w True \
        -o ${outDir}/03.register
```
I get the following error:
```
Namespace(conf='/mnt/image/FP200009107_E414_SC_20230614_193616_2.1.0.ipr', core=24, func=<class '__main__.Pipeline'>, gpu='-1', group=None, input='/mnt/image/FP200009107_E414_SC_20230614_193616_2.1.0.tar.gz', output='/mnt/output/03.register', protein=None, vis='/mnt/output/02.count/FP200009107_E414.raw.gef', whether_cell=True) []
[INFO 20231123-08-55-38 p28307 check_output main.py:112] The output result path is successfully created.
I1123 08:55:38.111819 28307 main.py:112] The output result path is successfully created.
[INFO 20231123-08-55-38 p28307 check_output main.py:119] The ipr file copied successfully.
I1123 08:55:38.118127 28307 main.py:119] The ipr file copied successfully.
[INFO 20231123-08-55-43 p28307 check_image main.py:86] The image compression package needs to decompress the .tif data format.
I1123 08:55:43.395092 28307 main.py:86] The image compression package needs to decompress the .tif data format.
[INFO 20231123-08-55-57 p28307 check_image main.py:98] Verify image data /mnt/image/FP200009107_E414_SC_20230614_193616_2.1.0.tar.gz file for registration
I1123 08:55:57.405136 28307 main.py:98] Verify image data /mnt/image/FP200009107_E414_SC_20230614_193616_2.1.0.tar.gz file for registration
[INFO 20231123-08-55-57 p28307 check_image main.py:104] Image verification successful.
I1123 08:55:57.406302 28307 main.py:104] Image verification successful.
[INFO 20231123-08-55-57 p28307 create_auto_manual_attrs main.py:254] Pipeline need to handle these subtask: ['stitch', 'tissueseg', 'cellseg', 'register'].
I1123 08:55:57.413671 28307 main.py:254] Pipeline need to handle these subtask: ['stitch', 'tissueseg', 'cellseg', 'register'].
[INFO 20231123-08-55-57 p28307 run main.py:441] >> Next do the Stitch task.
I1123 08:55:57.426168 28307 main.py:441] >> Next do the Stitch task.
Traceback (most recent call last):
  File "register/register-4.2.4/register/main.py", line 521, in <module>
  File "register/register-4.2.4/register/main.py", line 517, in main
  File "register/register-4.2.4/register/main.py", line 342, in __init__
  File "register/register-4.2.4/register/main.py", line 451, in run
  File "register/register-4.2.4/register/stitching/stitch.py", line 297, in stitch
  File "register/register-4.2.4/register/stitching/stitch.py", line 134, in __init__
  File "register/register-4.2.4/register/stitching/stitch.py", line 48, in __init__
  File "register/register-4.2.4/register/stitching/stitch.py", line 67, in get_stitch_info
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/usr/local/python3/lib/python3.8/site-packages/h5py/_hl/attrs.py", line 56, in __getitem__
    attr = h5a.open(self._id, self._e(name))
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5a.pyx", line 80, in h5py.h5a.open
KeyError: "Can't open attribute (can't locate attribute: 'WhichStitch')"

```
I am using singularity v3.8.3
Not sure if this is a bug.
I hope to get a response soon.
Regards,

**Comment by haolangchen** [comment]
Hello, I would like to ask you how to solve this problem. Because I also encountered the same problem

**Comment by haolangchen** [comment]
> Hi guys,
> 
> I am trying to run your pipeline (v7.0) on the olfactory test data. When I reach the part of "# Run SAW register to stitch microscope tile images into a panoramic image..." of the script and try running the command of register
> 
> ```
> singularity exec ${sif} register \
>         -i ${imageTarFile} \
>         -c ${iprFile} \
>         -v ${outDir}/02.count/${SN}.raw.gef \
>         -w True \
>         -o ${outDir}/03.register
> ```
> 
> I get the following error:
> 
> ```
> Namespace(conf='/mnt/image/FP200009107_E414_SC_20230614_193616_2.1.0.ipr', core=24, func=<class '__main__.Pipeline'>, gpu='-1', group=None, input='/mnt/image/FP200009107_E414_SC_20230614_193616_2.1.0.tar.gz', output='/mnt/output/03.register', protein=None, vis='/mnt/output/02.count/FP200009107_E414.raw.gef', whether_cell=True) []
> [INFO 20231123-08-55-38 p28307 check_output main.py:112] The output result path is successfully created.
> I1123 08:55:38.111819 28307 main.py:112] The output result path is successfully created.
> [INFO 20231123-08-55-38 p28307 check_output main.py:119] The ipr file copied successfully.
> I1123 08:55:38.118127 28307 main.py:119] The ipr file copied successfully.
> [INFO 20231123-08-55-43 p28307 check_image main.py:86] The image compression package needs to decompress the .tif data format.
> I1123 08:55:43.395092 28307 main.py:86] The image compression package needs to decompress the .tif data format.
> [INFO 20231123-08-55-57 p28307 check_image main.py:98] Verify image data /mnt/image/FP200009107_E414_SC_20230614_193616_2.1.0.tar.gz file for registration
> I1123 08:55:57.405136 28307 main.py:98] Verify image data /mnt/image/FP200009107_E414_SC_20230614_193616_2.1.0.tar.gz file for registration
> [INFO 20231123-08-55-57 p28307 check_image main.py:104] Image verification successful.
> I1123 08:55:57.406302 28307 main.py:104] Image verification successful.
> [INFO 20231123-08-55-57 p28307 create_auto_manual_attrs main.py:254] Pipeline need to handle these subtask: ['stitch', 'tissueseg', 'cellseg', 'register'].
> I1123 08:55:57.413671 28307 main.py:254] Pipeline need to handle these subtask: ['stitch', 'tissueseg', 'cellseg', 'register'].
> [INFO 20231123-08-55-57 p28307 run main.py:441] >> Next do the Stitch task.
> I1123 08:55:57.426168 28307 main.py:441] >> Next do the Stitch task.
> Traceback (most recent call last):
>   File "register/register-4.2.4/register/main.py", line 521, in <module>
>   File "register/register-4.2.4/register/main.py", line 517, in main
>   File "register/register-4.2.4/register/main.py", line 342, in __init__
>   File "register/register-4.2.4/register/main.py", line 451, in run
>   File "register/register-4.2.4/register/stitching/stitch.py", line 297, in stitch
>   File "register/register-4.2.4/register/stitching/stitch.py", line 134, in __init__
>   File "register/register-4.2.4/register/stitching/stitch.py", line 48, in __init__
>   File "register/register-4.2.4/register/stitching/stitch.py", line 67, in get_stitch_info
>   File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
>   File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
>   File "/usr/local/python3/lib/python3.8/site-packages/h5py/_hl/attrs.py", line 56, in __getitem__
>     attr = h5a.open(self._id, self._e(name))
>   File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
>   File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
>   File "h5py/h5a.pyx", line 80, in h5py.h5a.open
> KeyError: "Can't open attribute (can't locate attribute: 'WhichStitch')"
> ```
> 
> I am using singularity v3.8.3 Not sure if this is a bug. I hope to get a response soon. Regards,

Hello, I would like to ask you how to solve this problem. Because I also encountered the same problem
