### ISSUE TITLE
Manual Registration Part 2 Error

### ISSUE THREAD

**Issue by raforsyth** [STOmics/SAW#80]
I've successfully run the first part of the two part SAW pipeline in version 7.0 with manual image registration. However I'm running into a problem with the second part. I run the following code with the recommended specifications.
```
bash stereoPipeline_V7.0_manual_part2.sh \
    -SN "D01871D6" \
    -dataDir ${dataDir} \
    -speciesName "homoSapien" \
    -tissueType "sarcoma" \
    -registJson ${json}\
    -outDir "${outDir}" \
    -refIndex "$referenceDir/STAR" \
    -imageRecordFile ${ipr} \
    -imageCompressedFile ${tarball} \
    -sif "$sawDir/SAW_7.0.sif" \
    -threads 16 \
    -doCellbin Y \
```
I am then given the following output

```
Wed Nov 22 17:03:48 CET 2023  singularity check: pass, and singularity path is /bin/singularity
Wed Nov 22 17:03:48 CET 2023  singularity image file check: file exist and SIF path is SAW_7.0.sif
Wed Nov 22 17:03:48 CET 2023 => tissueCut start.......
[2023-11-22 17:03:50]	SAW-A50001:	 The parameter --sn must be given correctly
```

I'm deeply confused, since if I add an echo command for the ${SN} variable in stereoPipeline_V7.0_manual_part2.sh and the stereoPipeline_V7.0_manual_part1.sh while I run them, I get the same output. So it is getting my sample ID correctly but can't seem to use it in the singularity container properly.

What is going on?

**Comment by TheSallyGardens** [comment]
Hi!
You may have used the wrong parameter  for  stereoPipeline_V7.0_manual_part2.sh.https://github.com/STOmics/SAW/blob/main/Scripts/stereoPipeline_v7.0_manual_part2.sh

**Comment by raforsyth** [comment]
I'm not sure what problem the parameter would be, I can successfully run the full pipeline with the same parameters. But when I run with manual image registration it kicks up this issue. I have found that in part 1 output, I have a warning that I didn't spot before 
when it runs img2ipr I get the following error:
`[INFO 20231202-21-46-10 p144432 tar_decompress ipr_to_image.py:294] Extract files from tar.gz file completed.
[INFO 20231202-21-46-12 p144432 main ipr_to_image.py:728] Save ssDNA_fov_stitched_transformed.tif success.
[WARN 20231202-21-46-12 p144432 main ipr_to_image.py:735] Failed to generate transform_template.txt template.`

**Comment by TheSallyGardens** [comment]
Sorry, I have rerun stereoPipeline_V7.0_manual_part2.sh script, unable to reproduce your error ):.Please carefully check your input.

**Comment by OnkarMulay** [comment]
@raforsyth, have you solved this issue? I get the same issue.

Thanks
