### ISSUE TITLE
SAW-A10300:genomic Parameter vertification failed

### ISSUE THREAD

**Issue by RookieA1** [STOmics/SAW#82]
I am having a difficult problem running the sample data, I've checked all the parameters and I can't find the problem. Please let me know what is causing this. Here is my code, and the error message reported. 

![1702558773253](https://github.com/STOmics/SAW/assets/99639069/2687a9f1-eb38-4853-8393-7399b7075eea)

![1702558746950](https://github.com/STOmics/SAW/assets/99639069/76b191a2-be66-416e-91d1-1127c672ac72)

**Comment by Jinghao-Chen** [comment]
Hi, which indexed reference did you download from the sample data? _mouse_ or _mouse_v2_?

**Comment by RookieA1** [comment]
> Hi, which indexed reference did you download from the sample data? _mouse_ or _mouse_v2_?

Hi, the reference genome I'm using was downloaded from Test_Data, which comes with the test data, and I don't know its exact version information. That's what I'm confused about, why the reference genome supplied itself is also incorrect.

**Comment by Jinghao-Chen** [comment]
> Hi, the reference genome I'm using was downloaded from Test_Data, which comes with the test data, and I don't know its exact version information. That's what I'm confused about, why the reference genome supplied itself is also incorrect.

I'm sorry that the version of the reference in Test_Data->SS200000135TL_D1_v5_brain, was not compatible with SAW V6.1 and above.
It is recommended that you could refer to "script/pre_buildIndexedRef" to rebuild the reference using the genome.fa and genes.gtf, or you could also download the SAW_Demo_Data/reference/mouse_v2 or mouse_v2_rRNA from Test_Data
![image](https://github.com/STOmics/SAW/assets/58293762/eecd7ada-885e-4c32-b75f-2efb3a89d12a)

**Comment by RookieA1** [comment]
> > Hi, the reference genome I'm using was downloaded from Test_Data, which comes with the test data, and I don't know its exact version information. That's what I'm confused about, why the reference genome supplied itself is also incorrect.
> 
> I'm sorry that the version of the reference in Test_Data->SS200000135TL_D1_v5_brain, was not compatible with SAW V6.1 and above. It is recommended that you could refer to "script/pre_buildIndexedRef" to rebuild the reference using the genome.fa and genes.gtf, or you could also download the SAW_Demo_Data/reference/mouse_v2 or mouse_v2_rRNA from Test_Data ![image](https://private-user-images.githubusercontent.com/58293762/290540297-eecd7ada-885e-4c32-b75f-2efb3a89d12a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI1NjM1NDUsIm5iZiI6MTcwMjU2MzI0NSwicGF0aCI6Ii81ODI5Mzc2Mi8yOTA1NDAyOTctZWVjZDdhZGEtODg1ZS00YzMyLWI3NWYtMmVmYjNhODlkMTJhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE0VDE0MTQwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMyYjUwZTRhZGUyNmQ5NzhhZDI0YTkyYWJhNTUyMTYyMDExYjU4YTI4YzY4MTA4NWFmN2NjZTNkMTk0NDQ3YTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9JzJfpPovlq71DGPtaB-EvNtSwXTuGdBZ9PtKyNYA-0)

Thank you for your reply，I will download the right reference to test it.

**Comment by RookieA1** [comment]
> > Hi, the reference genome I'm using was downloaded from Test_Data, which comes with the test data, and I don't know its exact version information. That's what I'm confused about, why the reference genome supplied itself is also incorrect.
> 
> I'm sorry that the version of the reference in Test_Data->SS200000135TL_D1_v5_brain, was not compatible with SAW V6.1 and above. It is recommended that you could refer to "script/pre_buildIndexedRef" to rebuild the reference using the genome.fa and genes.gtf, or you could also download the SAW_Demo_Data/reference/mouse_v2 or mouse_v2_rRNA from Test_Data ![image](https://private-user-images.githubusercontent.com/58293762/290540297-eecd7ada-885e-4c32-b75f-2efb3a89d12a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI4ODg0MTEsIm5iZiI6MTcwMjg4ODExMSwicGF0aCI6Ii81ODI5Mzc2Mi8yOTA1NDAyOTctZWVjZDdhZGEtODg1ZS00YzMyLWI3NWYtMmVmYjNhODlkMTJhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE4VDA4MjgzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA1OGVkYjg4YTQwYjNhYjg1MmJkN2JmNWZlZWZmMzM2YTY3NGExMDNjOWMyZmU0MTQ3NDc0MDc1ZWU1ZmIxMTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.sbys-mEMAkPkO0DURH8c7BqmCmTfJ8_fE8KC-wHhdxk)

Hi, I have encountered another problem in the register step, it says SAW-A40001: IPRVersion field is missing. May I ask if this error is related to the fact that the image file in the sample data is not suitable for SAW version 7.0. Is this error related to the fact that the image file in the sample data is not suitable for 7.0 SAW, or that there is some parameter that I have missed, or that my environment is not fully configured?
![9d54119b9344e1f180d7dfa4fd3522b](https://github.com/STOmics/SAW/assets/99639069/ea213438-86ae-47f2-a114-4fc8f65f1d49)

**Comment by Jinghao-Chen** [comment]
Yes, the error is related to the fact that the image file in the sample data is not suitable for SAW version 7.0. The ipr and tar.gz were outputted by ImageStudio, a software for image quality control. The ipr and tar.gz files were generated by an old version of ImageStudio and do not suitable for SAW 7.0.0. If you still want to use this image, you can refer to the manual of ImageStudio and use the latest version of ImageStudio to perform QC operations on tar.gz

**Comment by RookieA1** [comment]
> ImageStudio

Thank you for your patient reply!

**Comment by RookieA1** [comment]
> Yes, the error is related to the fact that the image file in the sample data is not suitable for SAW version 7.0. The ipr and tar.gz were outputted by ImageStudio, a software for image quality control. The ipr and tar.gz files were generated by an old version of ImageStudio and do not suitable for SAW 7.0.0. If you still want to use this image, you can refer to the manual of ImageStudio and use the latest version of ImageStudio to perform QC operations on tar.gz

Thank you for your patient reply!

**Comment by RookieA1** [comment]
> Yes, the error is related to the fact that the image file in the sample data is not suitable for SAW version 7.0. The ipr and tar.gz were outputted by ImageStudio, a software for image quality control. The ipr and tar.gz files were generated by an old version of ImageStudio and do not suitable for SAW 7.0.0. If you still want to use this image, you can refer to the manual of ImageStudio and use the latest version of ImageStudio to perform QC operations on tar.gz

I'm sorry to bother you again, but I'm once again having problems running in practice and looking for advice. Which module's version is specifically too low to cause the error reported here? Actually the environment I'm running on is pulled directly via “ singularity build SAW_7.0.sif docker://stomics/saw:07.0.0”, so there shouldn't be a low version.
![image](https://github.com/STOmics/SAW/assets/99639069/bfe9deab-314d-498e-9e8b-544dd091bbd9)

**Comment by Jinghao-Chen** [comment]
Hi, which version of ImageStudio did you use to generate B03204F112_SCL001_S.tar.gz and B03204F112_SCL001_S.ipr? This error is often due to the version of ImageStudio being too low and not suitable for SAW 7.0.0. You can use the latest version of imagestudio (>=3.0.0) to rerun the quality control on your image to regenerate .tar.gz and .ipr files.
In addition, please try not to change the names of .tar.gz and ipr at will, otherwise it will cause some exceptions.

**Comment by RookieA1** [comment]
> Hi, which version of ImageStudio did you use to generate B03204F112_SCL001_S.tar.gz and B03204F112_SCL001_S.ipr? This error is often due to the version of ImageStudio being too low and not suitable for SAW 7.0.0. You can use the latest version of imagestudio (>=3.0.0) to rerun the quality control on your image to regenerate .tar.gz and .ipr files. In addition, please try not to change the names of .tar.gz and ipr at will, otherwise it will cause some exceptions.

Hi, after talking with the technician I found out that the image file I am using is based on ImageStudio V3 output and the name of the file has not been changed, but the above error still occurs, is there any other possible reason?

**Comment by Jinghao-Chen** [comment]
@RookieA1 Hi, could you share your B03204F112_SCL001_S.ipr file?

**Comment by RookieA1** [comment]
> @RookieA1 Hi, could you share your B03204F112_SCL001_S.ipr file?

Hi, This sample‘s image file didn't pass QC , so I followed the process of using ImageStuido to tissue cut and then manually align it, but when I run the shell for stereoPipeline_v7.0_manual_part2 there is still a problem, could you please tell me what is the cause of this?
![image](https://github.com/STOmics/SAW/assets/99639069/8f3790fb-ce15-4b6b-a99c-4f91182652c9)

**Comment by Jinghao-Chen** [comment]
@RookieA1 Hi, because you did not do cell segmentation, please replace '-d tissue cell' with '-d tissue' and try again.

**Comment by RookieA1** [comment]
> @RookieA1 Hi, because you did not do cell segmentation, please replace '-d tissue cell' with '-d tissue' and try again.

Hi，is the '-d' parameter part of stereoPipeline_v7.0_manual_part2.sh?  I don't see it in the documentation, I added it manually and ran it with the same error.

**Comment by Jinghao-Chen** [comment]
@RookieA1 If you ran stereoPipeline_v7.0_manual_part2.sh, please replace '-doCellBin Y' with '-doCellBin N'

**Comment by RookieA1** [comment]
> @RookieA1 If you ran stereoPipeline_v7.0_manual_part2.sh, please replace '-doCellBin Y' with '-doCellBin N'

Many thanks!
