### ISSUE TITLE
SAW-A40001:    The version of 0.1.0 is too low to deliver automatic registration

### ISSUE THREAD

**Issue by QAU-JackZhang** [STOmics/SAW#83]
saw version, 7.0
Use the v7 script to run automatically, but an error is still reported when registering manually.

**Comment by qiuyixmm** [comment]
I have the same error when running SAW v7. The error message was reported as follows:
 `[INFO 20231221-19-27-54 p116295 check_image main.py:104] Image verification successful. 
I1221 19:27:54.816316 116295 main.py:104] Image verification successful.  
[ERRO 20231221-19-27-54 p116295 create_auto_manual_attrs main.py:210] SAW-A40001:    The version of 0.1.0 is too low to deliver automatic registration.
E1221 19:27:54.817309 116295 main.py:210] SAW-A40001:    The version of 0.1.0 is too low to deliver automatic registration.
Traceback (most recent call last):
  File "register/register-4.2.4/register/main.py", line 521, in <module>
  File "register/register-4.2.4/register/main.py", line 517, in main
  File "register/register-4.2.4/register/main.py", line 335, in __init__
  File "register/register-4.2.4/register/main.py", line 211, in create_auto_manual_attrs
Exception: SAW-A40001:    The version of 0.1.0 is too low to deliver automatic registration.`

Thanks!

**Comment by Jinghao-Chen** [comment]
@QAU-JackZhang @qiuyixmm Hi, which version of ImageStudio did you use to generate .tar.gz and .ipr? This error is often due to the version of ImageStudio being too low and not suitable for SAW 7.0.0. You can use the latest version of imagestudio (>=3.0.0) and StereoMap(>=3.0.0)

**Comment by qiuyixmm** [comment]
> @QAU-JackZhang @qiuyixmm Hi, which version of ImageStudio did you use to generate .tar.gz and .ipr? This error is often due to the version of ImageStudio being too low and not suitable for SAW 7.0.0. You can use the latest version of imagestudio (>=3.0.0) and StereoMap(>=3.0.0)

Hello,
The .tar.gz and .ipr files were provided by BGI of the US, and I don't know the version of ImageStudio they used.  According to your kind suggestion, I want to use the ImageStudio with version>=3.0.0 to regenerate .tar.gz and .ipr files and use newly generated files as input files running SAW workflow. What are the input files for the ImageStudio software?

Best,

**Comment by Jinghao-Chen** [comment]
> > @QAU-JackZhang @qiuyixmm Hi, which version of ImageStudio did you use to generate .tar.gz and .ipr? This error is often due to the version of ImageStudio being too low and not suitable for SAW 7.0.0. You can use the latest version of imagestudio (>=3.0.0) and StereoMap(>=3.0.0)
> 
> Hello, The .tar.gz and .ipr files were provided by BGI of the US, and I don't know the version of ImageStudio they used. According to your kind suggestion, I want to use the ImageStudio with version>=3.0.0 to regenerate .tar.gz and .ipr files and use newly generated files as input files running SAW workflow. What are the input files for the ImageStudio software?
> 
> Best,

Hi, input files for ImageStudio:QC are the images from microscope, or you could use the .tar.gz before. For more details, please refer to the manual of ImageStudio

**Comment by qiuyixmm** [comment]
> > > @QAU-JackZhang @qiuyixmm Hi, which version of ImageStudio did you use to generate .tar.gz and .ipr? This error is often due to the version of ImageStudio being too low and not suitable for SAW 7.0.0. You can use the latest version of imagestudio (>=3.0.0) and StereoMap(>=3.0.0)
> > 
> > 
> > Hello, The .tar.gz and .ipr files were provided by BGI of the US, and I don't know the version of ImageStudio they used. According to your kind suggestion, I want to use the ImageStudio with version>=3.0.0 to regenerate .tar.gz and .ipr files and use newly generated files as input files running SAW workflow. What are the input files for the ImageStudio software?
> > Best,
> 
> Hi, input files for ImageStudio:QC are the images from microscope, or you could use the .tar.gz before. For more details, please refer to the manual of ImageStudio

OK. Many thanks!

**Comment by QAU-JackZhang** [comment]
> > > @QAU-JackZhang @qiuyixmm Hi, which version of ImageStudio did you use to generate .tar.gz and .ipr? This error is often due to the version of ImageStudio being too low and not suitable for SAW 7.0.0. You can use the latest version of imagestudio (>=3.0.0) and StereoMap(>=3.0.0)
> > 
> > 
> > Hello, The .tar.gz and .ipr files were provided by BGI of the US, and I don't know the version of ImageStudio they used. According to your kind suggestion, I want to use the ImageStudio with version>=3.0.0 to regenerate .tar.gz and .ipr files and use newly generated files as input files running SAW workflow. What are the input files for the ImageStudio software?
> > Best,
> 
> Hi, input files for ImageStudio:QC are the images from microscope, or you could use the .tar.gz before. For more details, please refer to the manual of ImageStudio

Thanks, this question will be deal.
