### ISSUE TITLE
report：KeyError: 'mapped_reads'

### ISSUE THREAD

**Issue by hgl2017** [STOmics/SAW#84]
I have encountered an issue while running the code. I am using the test data provided in the given URL, and I did not encounter any errors in the preceding steps.I am receiving a KeyError in the file handleReport_develop.py, specifically in line 332, with the error message "KeyError: 'mapped_reads'". I have thoroughly reviewed the code and ensured that the key 'mapped_reads' is present in the dictionary being accessed. The error is as follow:
Traceback (most recent call last):
  File "report/handleReport_main.py", line 451, in <module>
  File "report/handleReport_main.py", line 148, in main
  File "report/handleReport_develop.py", line 82, in run
  File "report/handleReport_develop.py", line 332, in filter_result
KeyError: 'mapped_reads'
My code is as follow:
outDir=/path/csna/test_out
SN=FP200009107_E414
lane=V350156884_L02
imageIPR=$(find ${outDir}/03.register -maxdepth 1 -name ${SN}*.ipr | head -1)
tissue_type=undefine
species_name=mouse
reference_index=STAR_SJ100
mkdir -p ${outDir}/07.report
report \
-m ${outDir}/01.mapping/${lane}_barcodeMap.stat \
-a ${outDir}/01.mapping/${lane}.Log.final.out \
-g ${outDir}/02.count/${SN}.Aligned.sortedByCoord.out.merge.q10.dedup.target.bam.summary.stat \
-l ${outDir}/04.tissuecut/tissuecut.stat \
-n ${outDir}/04.tissuecut/${SN}.gef \
-d ${outDir}/05.spatialcluster/${SN}.spatial.cluster.h5ad \
-b ${outDir}/04.tissuecut/tissue_fig/scatter_200x200_MID_gene_counts.png \
-v ${outDir}/04.tissuecut/tissue_fig/violin_200x200_MID_gene.png \
-c ${outDir}/04.tissuecut/tissue_fig/statistic_200x200_MID_gene_DNB.png \
--bin20Saturation ${outDir}/04.tissuecut/tissue_fig/scatter_50x50_MID_gene_counts.png \
--bin20violin ${outDir}/04.tissuecut/tissue_fig/violin_50x50_MID_gene.png \
--bin20MIDGeneDNB ${outDir}/04.tissuecut/tissue_fig/statistic_50x50_MID_gene_DNB.png \
--bin100violin ${outDir}/04.tissuecut/tissue_fig/violin_100x100_MID_gene.png \
--bin100MIDGeneDNB ${outDir}/04.tissuecut/tissue_fig/statistic_100x100_MID_gene_DNB.png \
--bin150Saturation ${outDir}/04.tissuecut/tissue_fig/scatter_150x150_MID_gene_counts.png \
--bin150violin ${outDir}/04.tissuecut/tissue_fig/violin_150x150_MID_gene.png \
--bin150MIDGeneDNB ${outDir}/04.tissuecut/tissue_fig/statistic_150x150_MID_gene_DNB.png \
 --cellBinGef ${outDir}/041.cellcut/${SN}.cellbin.gef \
 --cellCluster ${outDir}/051.cellcluster/${SN}.cell.cluster.h5ad \
-i ${outDir}/03.register/${SN}.rpi \
-r standard_version \
-s ${SN} \
--pipelineVersion SAW_6.1 \
--iprFile ${imageIPR} \
--species ${species_name} \
--tissue ${tissue_type} \
--reference ${reference_index} \
-o ${outDir}/07.report

**Comment by Jinghao-Chen** [comment]
@hgl2017 Hi, would you mind outputting ${outDir}/01.mapping/${lane}_barcodeMap.stat to us?
In addition, if you used singularity, please confirm that the relevant path has been successfully mounted and the relevant stat file exists.

**Comment by hgl2017** [comment]
Thank you for your prompt response. The path you mentioned, ${outDir}/01.mapping/${lane}_barcodeMap.stat, corresponds to the file named V350156884_L02_barcodeMap.stat. I have indeed used Singularity, and I can confirm that the relevant path has been successfully mounted and that the corresponding stat file exists.

cat V350156884_L02_barcodeMap.stat
--- cmd:  /opt/saw_v6.1.0_software/pipeline/mapping/bcSTAR --outSAMattributes spatial --outSAMtype BAM SortedByCoordinate --genomeDir mypath/mm10_ref/STAR_SJ100 --runThreadN 50 --outFileNamePrefix mypath/test_out/01.mapping/V350156884_L02. --sysShell /bin/bash --stParaFile V350156884_L02.bcPara --readNameSeparator " " --limitBAMsortRAM 385828801240 --limitOutSJcollapsed 10000000 --limitIObufferSize=280000000 --outBAMsortingBinsN 200 --outFilterMultimapNmax 100 --winAnchorMultimapNmax 100 --outSAMmultNmax 1

--- compile: Tue Jul 4 13:31:51 CST 2023
--- Info: v2.1.1 (based on STAR 2.7.2b) is released after optimization by BGI. - 
Jan 12 07:14:15 ..... started bcSTAR run
--- WARN: parameter - out is not supported in this version.
--- Info: read-1 mypath/test_Data/FP200009107_E414_v6.1_olfactory_bulb/reads/V350156884_L02_read_1.fq.gz
--- Info: read-2 mypath/test_Data/FP200009107_E414_v6.1_olfactory_bulb/reads/V350156884_L02_read_2.fq.gz
--- Info: time for creating barcode map - 39 s, size of bcmap - 181013097
Jan 12 07:14:55 ..... loading genome
--- Info: time for loading index - 69.0379 s , the index occupy 35.6055 GB
--- Info: time for loading index and barcode map - 108.728 s 	1.81213 min 
Jan 12 07:16:05 ..... started mapping
--- Info: IO wait for empty buf: 1, accumulative wait time: 125993 ms
Jan 12 07:24:32 ..... finished mapping
--- Info: time for mapping reads - 506.907 s 	8.44846 min 	VmRSS - 91 GB
--- Info: CID wait for full buf: 1462, accumulative wait time: 479466 ms
--- Info: time for counting CID - 369.523 s, and the num of CID is 26235765
Jan 12 07:30:56 ..... started sorting BAM
--- Info: original peak storage - 46 GB, compressed peak storage - 15 GB, vmRSS - 4 GB.
--- Info: time for merging BAM - 59.8093 s 	0.996822 min 
--- Info: time for sorting BAM - 114.984 s 	1.9164 min 
Jan 12 07:32:51 ..... finished successfully

**Comment by Jinghao-Chen** [comment]
Hi, based on the file content you provided, I guess you may used SAW 6.1 and stereoPipeline.sh ≤v6.0.0? If so, please use the report step in stereoPipeline_v6.1.sh in the v6.1 branch, because barcodeMap.stat was replaced by CIDMap.stat in v6.1. You could also confirm whether the CIDMap.stat exists and replace barcodeMap.stat with it in your script.

**Comment by hgl2017** [comment]
Thank you for your message. I appreciate your prompt response and understanding. I apologize for any confusion caused by my previous message. I now understand that the problem was indeed due to the use of the incorrect script version (6.0 instead of 6.1). I have made the necessary correction by replacing 'barcodeMap.stat' with 'CIDMap.stat' in my script, and it is now functioning correctly.

I apologize for any inconvenience I may have caused, and I sincerely thank you for your assistance.
