### ISSUE TITLE
stereo.core.StPipeline.find_marker_genes in multi-sample

### ISSUE THREAD

**Issue by sparkumr** [STOmics/SAW#85]
stereo.core.StPipeline.find_marker_genes： The set control group cannot be identified in the multi-sample, and when the program is running, it will only compare the difference between the case group and all the other groups

**Comment by Jinghao-Chen** [comment]
Hi, if you are using Stereopy, you could submit an issue on the stereopy page.
https://github.com/STOmics/Stereopy/issues

Best wishes!

**Comment by sparkumr** [comment]
> Hi, if you are using Stereopy, you could submit an issue on the stereopy page. https://github.com/STOmics/Stereopy/issues
> 
> Best wishes!

oh,thank you!
