### ISSUE TITLE
 fault(genomic Parameter verification failed.) on Mapping

### ISSUE THREAD

**Issue by ultraypy** [STOmics/SAW#87]
Hi, I'm using stereoPipeline_v7.0.sh to analyse SS200000464BL_C4_v5_heart demo data，when the mapping is going on，there is an error : 

--- Error: [2024-1-21 0:11:28] SAW-A10300: genomic Parameter verification failed.
bcSTAR: ReadsParse.cpp:1238: BGI::StarRef::StarRef(BGI::StarParam&): Assertion `false' failed.
/usr/local/bin/mapping: line 1: 179491 Aborted                 (core dumped) /opt/saw_v7.0.0_software/pipeline/mapping/bcSTAR $*
Command exited with non-zero status 134

here is my run.sh.
<img width="889" alt="image" src="https://github.com/STOmics/SAW/assets/56919476/c3246b14-c3d1-48ee-b45a-a8fb33ce637d">

I didn't create an index because there seemed to be an index file in the data.
<img width="384" alt="image" src="https://github.com/STOmics/SAW/assets/56919476/8363e68b-f77e-4f7e-b29c-58213ea3e4c4">

I've no idea about this issue.
Thanks for your timely reply!

**Comment by Jinghao-Chen** [comment]
Hi,  I'm sorry that the reference index in this version of this test data is no longer suitable for SAW 6.1 or above. You could refer to the script, [script/pre_buildIndexedRef](https://github.com/STOmics/SAW/tree/main/Scripts/pre_buildIndexedRef), to reuse genome.fa and genes.gtf to build a new index.

**Comment by Jinghao-Chen** [comment]
By the way, the .ipr and .tar.gz files are not suitable for SAW 7.0 but suitalble for SAW 6.x. If you still want to run SAW 7.0, it is recommended that you could use another test data C02533C1_v7.0_kidney, or download ImageStudio and reprocess the SS200000464BL_C4_SC_20230207_143441_1.0.0.tar.gz.
