### ISSUE TITLE
 Issues with Image Registration: How to Obtain Upstream Files Compatible with MOSTA from SAW Analysis

### ISSUE THREAD

**Issue by LiTing99-cutie** [STOmics/SAW#88]
I have recently been testing the SS200000135TL_D1 sample using your SAW7.0 software package. Specifically, I utilized the stereoPipeline_v7.0.sh. During this process, I encountered an issue in the registration step, where I received an error message indicating that the "IPRVersion field is missing."

Based on this issue discussion [https://github.com/STOmics/SAW/issues/82], it seems the problem may be due to incompatibility between the image file's processing version and SAW7.0. Although there is a suggestion to reprocess the image with a new processing version, my knowledge in image processing is quite limited. Therefore, I opted to use SAW5.1 instead, which allowed me to obtain the registration results from the count output file.

My query revolves around how to derive the following files from the SAW analysis steps, as found on https://db.cngb.org/stomics/mosta/download/:
https://ftp.cngb.org/pub/SciRAID/stomics/STDS0000058/Image/Mouse_brain_Adult.tif
https://ftp.cngb.org/pub/SciRAID/stomics/STDS0000058/Bin1_matrix/Mouse_brain_Adult_GEM_bin1.tsv.gz

From my preliminary analysis, I understand that the tif file is a registered tif, and GEM_bin1 is the gef transformed into gem after tissue segmentation. However, upon examining my processed tif file, which seems similar in shape, it appears that the coordinates do not align correctly when imported into Spateo.
![微信截图_20240127145706](https://github.com/STOmics/SAW/assets/71929719/cb095897-c5fc-42b9-b720-82cc78fa8ebe)

I am particularly puzzled by the registration output, as it seems inverted compared to the Mouse_brain_Adult.tif file.
![微信截图_20240127145857](https://github.com/STOmics/SAW/assets/71929719/de019745-f4ce-45f6-a8d3-3e73c1fdad65)

Could you guide me on how to correctly obtain the processed tif and gem files as presented in MOSTA? Is the image mismatch issue related to my usage of an incorrect version of SAW in the registration step, or is there another reason for this discrepancy?

Looking forward to your guidance and assistance.

Best regards,

Ting

**Comment by Jinghao-Chen** [comment]
Hi, _ssDNA_SS200000135TL_D1_regist.tif_ is the image registered with the gene matrix, while _Mouse_brain_Adult.tif_ is the original image from microscope, so there may be flipping. The gem file is located in the 04. issuecut directory. If you want to quickly check the alignment, you can use StereoMap to import _03.register/SS200000135TL_D1.rpi_ and _04. issuecut/SS200000135TL_D1.gef_, if misalignment is found, please refer to instructions of StereoMap for manual registration.
In addition, the gem file output by SAW has offset x and offet y, which may cause the misalignment you mentioned. You could refer to the header of the gem file and subtract the offset from the coordinate x and y before importing it into the software.

Best wishes!

**Comment by LiTing99-cutie** [comment]
> Hi, _ssDNA_SS200000135TL_D1_regist.tif_ is the image registered with the gene matrix, while _Mouse_brain_Adult.tif_ is the original image from microscope, so there may be flipping. The gem file is located in the 04. issuecut directory. If you want to quickly check the alignment, you can use StereoMap to import _03.register/SS200000135TL_D1.rpi_ and _04. issuecut/SS200000135TL_D1.gef_, if misalignment is found, please refer to instructions of StereoMap for manual registration. In addition, the gem file output by SAW has offset x and offet y, which may cause the misalignment you mentioned. You could refer to the header of the gem file and subtract the offset from the coordinate x and y before importing it into the software.
> 
> Best wishes!

Hello, and thank you for your response!

I have attempted to import the 04.tissuecut/SS200000135TL_D1.gem and 03.register/ssDNA_SS200000135TL_D1_regist.tif into Spateo and noticed that they do not align well.

`adata3 = st.io.read_bgi_agg(
    '../data/raw/SAW_test_data/D1_v5_brain/output/04.tissuecut/SS200000135TL_D1.gem','../data/raw/SAW_test_data/D1_v5_brain/output/03.register/ssDNA_SS200000135TL_D1_regist.tif',
)
adata3
st.pl.imshow(adata3, 'stain')
adata3.layers['unspliced'] = adata3.X
st.pl.imshow(adata3, 'unspliced', alpha=0.6, cmap='Reds', vmax=2, use_scale=False)
`
![image](https://github.com/STOmics/SAW/assets/71929719/68a0b19d-db40-4626-bf78-320eb5ef2f2e)

![image](https://github.com/STOmics/SAW/assets/71929719/ba8d3eb4-9d2c-4199-a22b-084b641b1cb4)

However, after rotating the ssDNA_SS200000135TL_D1_regist.tif image by 90 degrees clockwise and applying a horizontal flip, or using Mouse_brain_Adult.tif, they align quite well in Spateo, although there are very slight differences in the n_obs and n_vars of the final adata.

Additionally, I checked the offset in the gem file you mentioned and found no offset present, i.e., the offset is zero.

`#FileFormat=GEMv0.1
#SortedBy=None
#BinType=Bin
#BinSize=1
#Omics=Transcriptomics
#Stereo-seqChip=SS200000135TL_D1
#OffsetX=0
#OffsetY=0
`

Moreover, my gem was converted from 04.tissuecut/SS200000135TL_D1.tissue.gef.

`singularity exec ./SAW_7.0.sif cellCut view \
-s SS200000135TL_D1 \
-i $dataDir/output/04.tissuecut/SS200000135TL_D1.tissue.gef \
-o $dataDir/output/04.tissuecut/SS200000135TL_D1.gem
`

I would like to know if it is reasonable to use my converted 04.tissuecut/SS200000135TL_D1.gem and the rotated and flipped ssDNA_SS200000135TL_D1_regist.tif for nuclear segmentation and cell segmentation in Spateo?

**Comment by Jinghao-Chen** [comment]
Hi, the coordinate processing method of Spateo may be slightly different from that of SAW. As shown in the figure below for Mouse_Brain_Adult.tif and Mouse_brain_Adult_GEM_bin1.tsv.gz, they are actually not aligned. 
![image](https://github.com/STOmics/SAW/assets/58293762/ba017832-149a-48f6-9399-a9ee1b60c089)
![image](https://github.com/STOmics/SAW/assets/58293762/6da39ceb-aa66-4d2e-9856-35b9aa48cf74)

Perhaps Spateo has performed some operations on the image, you could try to use 03.register/ssDNA_fov_stitched_transformed.tif, theoretically it is similar to Mouse_Brain_Adult.tif, which is the original image that has not been rotated or flipped by SAW. Alternatively, you could consult Spateo for help.

**Comment by LiTing99-cutie** [comment]
Thanks for your kindly and timely reply! And i will try to consult Spateo!
