### ISSUE TITLE
Inquiry on Manual Registration Process

### ISSUE THREAD

**Issue by JungTaeKim103** [STOmics/SAW#91]
Title: Inquiry on Manual Registration Process

I'm writing to seek clarification on what steps I should take next as I find myself confused following the SAW process. I have successfully obtained SN.gef and fov_stitched_transformed.rpi files. After opening SN.gef and fov_stitched_transformed.rpi, I adjusted their positions and clicked submit to generate a Json file.

However, I'm unclear on what to do next. Should I be using the stereoPipeline_v7.0_manual_part2.sh script? 
Or
Do I need to rerun stereoPipeline_v7.0_manual_part1.sh and then proceed with stereoPipeline_v7.0_manual_part2.sh, inserting my Json file in the -registJson: manual registration json file section?

I would greatly appreciate a detailed response on the process.

**Comment by JungTaeKim103** [comment]
I tried below code. 

```
cd /home/users/Minhos/R/Stereoseq/ &&
bash stereoPipeline_v7.0_manual_part2.sh \
    -SN B******* \
    -DataDir /home/users/Minhos/R/Stereoseq/results_control/02.count/ \
    -registJson /home/users/Minhos/R/Stereoseq/results_control/03.register/Regist/20240207115016.regist.json \
    -speciesName Mouse \
    -tissueType Brain \
    -outDir /home/users/Minhos/R/Stereoseq/results_control_MR/ \
    -imageRecordFile /home/users/Minhos/R/Stereoseq/Mouse-Brain-Control/B*******_SC_20240117_135843_3.0.2.ipr \
    -imageCompressedFile /home/users/Minhos/R/Stereoseq/Mouse-Brain-Control/B*******_SC_20240117_135843_3.0.2.tar.gz \
    -doCellBin Y \
    -threads 20 \
    -sif /home/users/Minhos/SAW_7.0.sif
```
and I got the this error 
`[ERRO 20240213-18-09-42 p501356 _get_input semi_automatic.py:132] SAW-A40802:    -v or --vis Not found vis file in /home/users/Minhos/R/Stereoseq/results_control/02.count//02.count/B*******.raw.gef.`

Can you explain what is the gene expression matrix file?
I am confusing

**Comment by Jinghao-Chen** [comment]
Hi, I think you have run the SAW pipeline and get the gef file, therefore you could run the stereoPipeline_v7.0_manual_part2.sh. 
It is recommended that you may change the 
`-DataDir /home/users/Minhos/R/Stereoseq/results_control/02.count/ ` to
`-DataDir /home/users/Minhos/R/Stereoseq/results_control` and have a try, if you confirmed that /home/users/Minhos/R/Stereoseq/results_control/02.count/B*******.raw.gef exists.

**Comment by JungTaeKim103** [comment]
Thank you error is cleared
