### ISSUE TITLE
singularity exec  SAW_7.0.sif  failed

### ISSUE THREAD

**Issue by liangzhenhou** [STOmics/SAW#93]
'INFO:    Converting SIF file to temporary sandbox...
FATAL:   while extracting SAW_7.0.sif: root filesystem extraction failed: extract command failed: ERROR  : Failed to create user namespace: user namespace disabled
: exit status 1'

When I run 'singularity exec SAW_7.0.sif  mapping --runMode genomeGenerate' command, it raises this error. 
How to solve it for a non-root user, thank you!

**Comment by Jinghao-Chen** [comment]
Hi, for non-root user, we recommend solution as follow,
`export SINGULARITY_CACHEDIR=/path/to/build`
`singularity build SAW_version.sif docker:dockerhub_url`

**Comment by liangzhenhou** [comment]
> Hi, for non-root user, we recommend solution as follow, `export SINGULARITY_CACHEDIR=/path/to/build` `singularity build SAW_version.sif docker:dockerhub_url`

Thank you for your reply. I followed this solution, but I still get the same error. The singularity (version 3.8.6) is installed by conda 'conda install conda-forge::singularity'.

**Comment by Jinghao-Chen** [comment]
For singularity itself, you could try to contact your HPC admin to install singularity, refer the follow method when installing singularity as non-root user, or consider using docker
`./mconfig --without-suid --prefix=$PATH_YOU_WANT_TO_INSTALL`

Reference:
https://docs.sylabs.io/guides/3.9/admin-guide/installation.html#install-from-source
install-from-source->Unprivileged (non-setuid) Installation

**Comment by liangzhenhou** [comment]
> For singularity itself, you could try to contact your HPC admin to install singularity, refer the follow method when installing singularity as non-root user, or consider using docker `./mconfig --without-suid --prefix=$PATH_YOU_WANT_TO_INSTALL`
> 
> Reference: https://docs.sylabs.io/guides/3.9/admin-guide/installation.html#install-from-source install-from-source->Unprivileged (non-setuid) Installation

Great, thanks! If I want to use Stereopy software to do a cell segmentaion.  From SAW output, the bin1 gene expression file I have got, could you tell me how to get the ssDNA .tif image file?

**Comment by Jinghao-Chen** [comment]
Hi, you could get it from 03.register, named as ${SN_number}.regist.tif.
I'm not sure if there are other tif files in your directory. Please obtain the file with the suffix 'regist.tif', whose coordinates are consistent with the gene expression matrix.

**Comment by liangzhenhou** [comment]
> Hi, you could get it from 03.register, named as ${SN_number}.regist.tif. I'm not sure if there are other tif files in your directory. Please obtain the file with the suffix 'regist.tif', whose coordinates are consistent with the gene expression matrix.

Thank you! When I run SAW whole pipeline to get 03.register,I met this error https://github.com/STOmics/SAW/issues/96 .  Could help me to fix it?
