### ISSUE TITLE
partially initialized module 'cv2' has no attribute 'gapi_wip_gst_GStreamerPipeline'

### ISSUE THREAD

**Issue by liangzhenhou** [STOmics/SAW#96]
<img width="803" alt="1708650368333" src="https://github.com/STOmics/SAW/assets/44781595/9e12f3d2-787d-4fed-bbf8-260f3e0d279c">

at 'image processing and registration start' step, it raises above error.
Is there a soultion? Thank you!

**Comment by liangzhenhou** [comment]
/usr/bin/time -v singularity exec ${sif} register \
        -i ${imageTarFile} \
        -c ${iprFile} \
        -v ${outDir}/02.count/${SN}.raw.gef \
        -w True --core ${threads} \
        -o ${outDir}/03.register

When run this step, it raises above error. The SAW version is 7.0.

**Comment by Jinghao-Chen** [comment]
This is generally caused by package conflicts in the system environment. I'm sorry that we have less relevant experience and you could try to reconstruct the conda environment.

**Comment by liangzhenhou** [comment]
> This is generally caused by package conflicts in the system environment. I'm sorry that we have less relevant experience and you could try to reconstruct the conda environment.

Thank for your advice! it works for me

**Comment by liangzhenhou** [comment]
<img width="805" alt="1708693647083" src="https://github.com/STOmics/SAW/assets/44781595/39fa579e-1fb2-4eae-899c-c13cc5b06278">
Whether it indicate that the imageRecordFile ipr file is invalid?

**Comment by Jinghao-Chen** [comment]
It means the image did not pass QC in ImageStudio, you may need to do manual tissue segmentation in ImageStudio and manual registration in StereoMap, refer to 'Scripts/stereoPipeline_v7.0_manual_part1.sh' and 'Scripts/stereoPipeline_v7.0_manual_part2.sh' .

**Comment by liangzhenhou** [comment]
> It means the image did not pass QC in ImageStudio, you may need to do manual tissue segmentation in ImageStudio and manual registration in StereoMap, refer to 'Scripts/stereoPipeline_v7.0_manual_part1.sh' and 'Scripts/stereoPipeline_v7.0_manual_part2.sh' .

Thank you! It is very helpful.
