### ISSUE TITLE
upgrade ipr and tar image

### ISSUE THREAD

**Issue by DMaspero** [STOmics/SAW#97]
Hi!
I have the correctly processed stained image saved as an .ipr and .tar.gz file (v2) which I have already used to process the raw data with SAW v6.

I now need to reprocess this data and would like to use the latest version of the SAW pipeline (v7), which only accepts .ipr v3 images.
Therefore, I was wondering what is the best way to convert stained images into the latest version of the format.

Could you help me?

Thank you for your assistance!

**Comment by TheSallyGardens** [comment]
@DMaspero Hi!
Using imageStudio V3 to go back to QC should help you!
